#!/usr/bin/env python3
"""Generate quiz questions for Fundamentals domain (100 questions)."""
import json
from pathlib import Path
OUTPUT = Path(__file__).parent.parent / "data" / "questions" / "fundamentals_generated.json"

def q(id,topic,domain,qtype,diff,question,answers,validation,keywords,explanation,hints):
    return {"id":id,"topic_id":topic,"domain":domain,"type":qtype,"difficulty":diff,
            "question":question,"correct_answers":answers,"validation_type":validation,
            "required_keywords":keywords,"explanation":explanation,"hints":hints}

QS = [
# OSI Model (10)
q("q-osi-02","osi-model","fundamentals","theory","easy","What is the function of the Data Link layer (Layer 2)?",["framing","frame delivery","mac addressing","physical addressing"],"contains_any",[],"Layer 2 handles framing, MAC addressing, and delivery on the local network segment.",["Think about MAC addresses and switches"]),
q("q-osi-03","osi-model","fundamentals","theory","easy","Which layer handles end-to-end delivery and error recovery?",["transport","layer 4","4"],"contains_any",[],"The Transport layer (Layer 4) provides end-to-end delivery, flow control, and error recovery.",["TCP and UDP live here"]),
q("q-osi-04","osi-model","fundamentals","theory","medium","At which OSI layer does a switch primarily operate?",["layer 2","data link","2"],"contains_any",[],"Switches operate at Layer 2 (Data Link) using MAC addresses to forward frames.",["Switches use MAC address tables"]),
q("q-osi-05","osi-model","fundamentals","theory","medium","What PDU (Protocol Data Unit) is used at Layer 4?",["segment","segments"],"contains_any",[],"Layer 4 uses segments (TCP) or datagrams (UDP) as its PDU.",["Think TCP..."]),
q("q-osi-06","osi-model","fundamentals","command","medium","What Wireshark display filter shows only traffic on a specific OSI Layer 4 port?",["tcp.port ==","tcp.port==","udp.port =="],"contains_any",[],"Use tcp.port == <number> or udp.port == <number> to filter by Layer 4 port.",["Wireshark uses dot notation for protocol fields"]),
# TCP/IP Model (5)
q("q-tcpip-01","tcp-ip-model","fundamentals","theory","easy","How many layers does the TCP/IP model have?",["4","four"],"contains_any",[],"The TCP/IP model has 4 layers: Network Access, Internet, Transport, Application.",["Less than OSI"]),
q("q-tcpip-02","tcp-ip-model","fundamentals","theory","medium","Which TCP/IP layer combines OSI layers 5, 6, and 7?",["application","application layer"],"contains_any",[],"The Application layer in TCP/IP combines Session, Presentation, and Application from OSI.",["The top layer"]),
q("q-tcpip-03","tcp-ip-model","fundamentals","scenario","medium","A web browser initiates an HTTPS connection. At which TCP/IP layer does TLS encryption occur?",["application","transport"],"contains_any",[],"TLS operates between Transport and Application layers. In TCP/IP model, it's considered part of the Application layer.",["Where does encryption happen?"]),
q("q-tcpip-04","tcp-ip-model","fundamentals","theory","easy","What protocol operates at the Internet layer of TCP/IP?",["ip","icmp","arp","internet protocol"],"contains_any",[],"IP, ICMP, and ARP operate at the Internet layer.",["Think about addressing"]),
q("q-tcpip-05","tcp-ip-model","fundamentals","theory","hard","What is the key difference between OSI and TCP/IP models in terms of practical implementation?",["tcp/ip is implemented","practical","real-world","actual protocols"],"contains_any",[],"TCP/IP model maps directly to real protocols and is actually implemented, while OSI is a theoretical reference model.",["One is theoretical, one is practical"]),
# Subnetting (10)
q("q-sub-01","subnetting","fundamentals","command","easy","What is the subnet mask for a /24 network?",["255.255.255.0"],"exact",[],"A /24 means 24 bits for network = 255.255.255.0.",["Count the bits: 8+8+8=24"]),
q("q-sub-02","subnetting","fundamentals","command","medium","How many usable host addresses are in a /26 subnet?",["62"],"exact",[],"A /26 has 6 host bits = 2^6 - 2 = 62 usable addresses.",["Subtract 2 for network and broadcast"]),
q("q-sub-03","subnetting","fundamentals","command","medium","What is the subnet mask for a /20 network?",["255.255.240.0"],"exact",[],"A /20 = 255.255.240.0 (20 bits = 8+8+4, so third octet = 11110000 = 240).",["Third octet has 4 network bits"]),
q("q-sub-04","subnetting","fundamentals","scenario","hard","You need to create 14 subnets from a /16 network. What prefix length should you use?",["20","/20"],"contains_any",[],"14 subnets needs 4 bits (2^4=16 >= 14). /16 + 4 = /20.",["How many bits to represent 14?"]),
q("q-sub-05","subnetting","fundamentals","command","medium","What is the broadcast address of 192.168.1.64/26?",["192.168.1.127"],"exact",[],"Network: 192.168.1.64, next network: 192.168.1.128, broadcast = 192.168.1.127.",["Broadcast is one less than next network"]),
q("q-sub-06","subnetting","fundamentals","command","hard","What is the network address for host 172.16.45.200/21?",["172.16.40.0"],"exact",[],"A /21 means third octet increments by 8 (256-248). 45/8=5 remainder 5, so network = 5*8=40.",["Third octet subnet size is 8"]),
q("q-sub-07","subnetting","fundamentals","theory","easy","What are the two addresses you cannot assign to hosts in a subnet?",["network and broadcast","network","broadcast"],"contains_any",[],"The network address (all host bits 0) and broadcast address (all host bits 1) cannot be assigned to hosts.",["First and last"]),
q("q-sub-08","subnetting","fundamentals","command","medium","How many /30 subnets can you create from a /24 network?",["64"],"exact",[],"A /24 has 8 host bits, /30 uses 6 for subnets = 2^6 = 64 subnets.",["Each /30 has 4 addresses"]),
q("q-sub-09","subnetting","fundamentals","scenario","medium","You need point-to-point links between routers. What prefix length wastes the least addresses?",["31","/31","30","/30"],"contains_any",[],"Use /31 (RFC 3021) for point-to-point links (2 addresses, no waste) or /30 (traditional, 2 usable).",["Point-to-point needs exactly 2 addresses"]),
q("q-sub-10","subnetting","fundamentals","command","hard","Convert 192.168.1.0/24 to CIDR notation if you need exactly 30 hosts per subnet.",["192.168.1.0/27","/27","27"],"contains_any",[],"30 hosts needs 5 host bits (2^5-2=30). Prefix = 32-5 = /27.",["How many bits for 30+2?"]),
# VLANs (8)
q("q-vlan-01","vlans","fundamentals","theory","easy","What is the default VLAN on most Cisco switches?",["vlan 1","1"],"contains_any",[],"VLAN 1 is the default VLAN — all ports are in VLAN 1 by default.",["The first one"]),
q("q-vlan-02","vlans","fundamentals","command","medium","What command assigns a switch port to VLAN 10 on Cisco IOS?",["switchport access vlan 10"],"contains_any",[],"Use 'switchport access vlan 10' in interface config mode.",["switchport access..."]),
q("q-vlan-03","vlans","fundamentals","theory","medium","What protocol is used to carry multiple VLANs over a single link?",["802.1q","dot1q","trunk","trunking"],"contains_any",[],"IEEE 802.1Q (dot1q) adds a 4-byte tag to frames for VLAN identification on trunk links.",["IEEE standard for VLAN tagging"]),
q("q-vlan-04","vlans","fundamentals","theory","medium","What is a native VLAN?",["untagged vlan on trunk","vlan that is untagged","frames without tags"],"contains_any",[],"The native VLAN carries untagged traffic on a trunk link. Frames in the native VLAN are sent without 802.1Q tags.",["What happens to untagged frames on a trunk?"]),
q("q-vlan-05","vlans","fundamentals","scenario","hard","Two switches are connected via a trunk. Switch A has native VLAN 1, Switch B has native VLAN 99. What happens?",["native vlan mismatch","mismatch","traffic leak","security issue"],"contains_any",[],"Native VLAN mismatch causes traffic leaking between VLANs — a security vulnerability. CDP/LLDP will report the mismatch.",["What if they disagree on which VLAN is untagged?"]),
q("q-vlan-06","vlans","fundamentals","command","medium","What command creates VLAN 100 named 'Engineering' on Cisco IOS?",["vlan 100","name engineering"],"contains_all",[],"Enter 'vlan 100' then 'name Engineering' in global config mode.",["Two commands needed"]),
q("q-vlan-07","vlans","fundamentals","theory","easy","Can devices in different VLANs communicate without a router?",["no","cannot","need router","need layer 3"],"contains_any",[],"VLANs are separate broadcast domains — inter-VLAN communication requires a Layer 3 device (router or L3 switch).",["VLANs isolate traffic"]),
q("q-vlan-08","vlans","fundamentals","theory","hard","What is VLAN hopping and how is it prevented?",["double tagging","switch spoofing","native vlan","trunk"],"contains_any",[],"VLAN hopping exploits native VLAN or DTP to access other VLANs. Prevent by: setting native VLAN to unused VLAN, disabling DTP, and using explicit trunk configuration.",["Two attack methods exist"]),
# DNS (8)
q("q-dns-01","dns-fundamentals","fundamentals","theory","easy","What port does DNS primarily use?",["53","port 53"],"contains_any",[],"DNS uses port 53 — UDP for queries, TCP for zone transfers and large responses.",["A well-known port number"]),
q("q-dns-02","dns-fundamentals","fundamentals","command","medium","What command queries DNS for the MX records of a domain on Linux?",["dig mx","nslookup -type=mx","dig -t mx","host -t mx"],"contains_any",[],"Use 'dig mx domain.com' or 'nslookup -type=mx domain.com' to query MX records.",["dig or nslookup with record type"]),
q("q-dns-03","dns-fundamentals","fundamentals","theory","medium","What is the difference between an A record and a CNAME record?",["a record maps to ip","cname is alias","a is address","cname points to another name"],"contains_any",[],"An A record maps a hostname to an IPv4 address. A CNAME creates an alias pointing to another hostname.",["One maps to IP, one maps to name"]),
q("q-dns-04","dns-fundamentals","fundamentals","theory","medium","What is a PTR record used for?",["reverse dns","reverse lookup","ip to name","reverse"],"contains_any",[],"PTR records map IP addresses to hostnames (reverse DNS lookup).",["The opposite of an A record"]),
q("q-dns-05","dns-fundamentals","fundamentals","scenario","hard","Your recursive DNS server is being used in a DDoS amplification attack. What should you configure?",["response rate limiting","acl","restrict recursion","rrl"],"contains_any",[],"Implement Response Rate Limiting (RRL), restrict recursion to internal clients only, and use ACLs to limit who can query.",["Limit who can use your resolver"]),
q("q-dns-06","dns-fundamentals","fundamentals","command","easy","What command flushes the DNS cache on Windows?",["ipconfig /flushdns","ipconfig/flushdns"],"contains_any",[],"Use 'ipconfig /flushdns' to clear the local DNS resolver cache on Windows.",["ipconfig with a flag"]),
q("q-dns-07","dns-fundamentals","fundamentals","theory","medium","What is DNS TTL and why does it matter?",["time to live","cache duration","how long cached","caching time"],"contains_any",[],"TTL (Time To Live) tells resolvers how long to cache a DNS response. Lower TTL = faster propagation of changes but more queries to authoritative servers.",["How long should answers be remembered?"]),
q("q-dns-08","dns-fundamentals","fundamentals","theory","hard","Explain the DNS resolution process for a new domain query.",["recursive","root","tld","authoritative","iterative"],"contains_any",[],"Client asks recursive resolver → resolver queries root servers → TLD servers → authoritative nameserver → returns answer to client.",["Multiple servers are involved"]),
# TCP (8)
q("q-tcp-01","tcp-protocol","fundamentals","theory","easy","What is the TCP three-way handshake sequence?",["syn syn-ack ack","syn, syn/ack, ack","syn synack ack"],"contains_any",[],"TCP three-way handshake: SYN → SYN-ACK → ACK. Establishes a reliable connection.",["Three steps to connect"]),
q("q-tcp-02","tcp-protocol","fundamentals","theory","medium","What TCP flag is used to gracefully close a connection?",["fin","FIN"],"contains_any",[],"The FIN flag initiates a graceful connection termination (four-way close: FIN, ACK, FIN, ACK).",["Finish..."]),
q("q-tcp-03","tcp-protocol","fundamentals","command","medium","What Wireshark filter shows only TCP SYN packets (new connections)?",["tcp.flags.syn==1 and tcp.flags.ack==0","tcp.flags.syn == 1 && tcp.flags.ack == 0","tcp.flags == 0x002"],"contains_any",[],"Filter for SYN=1 and ACK=0 to see only initial connection attempts.",["SYN without ACK"]),
q("q-tcp-04","tcp-protocol","fundamentals","theory","hard","What is TCP window scaling and when is it needed?",["larger window","window size","exceed 65535","high bandwidth"],"contains_any",[],"Window scaling (RFC 7323) allows TCP window sizes larger than 65535 bytes, needed for high-bandwidth or high-latency links.",["Default window size has a limit"]),
q("q-tcp-05","tcp-protocol","fundamentals","scenario","medium","You see many TCP RST packets from a server. What could this indicate?",["port closed","service down","firewall","connection refused","not listening"],"contains_any",[],"TCP RST indicates the port is closed, service crashed, firewall is rejecting, or connection state was lost.",["RST means rejection"]),
q("q-tcp-06","tcp-protocol","fundamentals","theory","medium","What is the difference between TCP and UDP?",["reliable","connection","ordered","unreliable","connectionless"],"contains_any",[],"TCP is connection-oriented, reliable, ordered delivery. UDP is connectionless, unreliable, no ordering — but faster and lower overhead.",["One guarantees delivery, one doesn't"]),
q("q-tcp-07","tcp-protocol","fundamentals","theory","hard","What is TCP Selective Acknowledgment (SACK)?",["retransmit only lost","selective retransmission","specific segments","not retransmit all"],"contains_any",[],"SACK allows the receiver to acknowledge non-contiguous blocks, so the sender only retransmits actually lost segments instead of everything after the gap.",["Smarter retransmission"]),
q("q-tcp-08","tcp-protocol","fundamentals","command","medium","What is the well-known port for HTTPS?",["443"],"exact",[],"HTTPS uses TCP port 443.",["Secure web"]),
# DHCP (5)
q("q-dhcp-01","dhcp","fundamentals","theory","easy","What are the four steps of DHCP address assignment?",["discover offer request ack","dora","discover, offer, request, acknowledge"],"contains_any",[],"DHCP DORA: Discover → Offer → Request → Acknowledge.",["DORA"]),
q("q-dhcp-02","dhcp","fundamentals","theory","medium","What happens when a DHCP lease expires?",["renew","release","request new","lose address"],"contains_any",[],"Client attempts renewal at 50% (T1) and 87.5% (T2) of lease time. If renewal fails, the client loses the IP and must restart DORA.",["Client tries to keep its address"]),
q("q-dhcp-03","dhcp","fundamentals","command","medium","What command releases and renews a DHCP lease on Windows?",["ipconfig /release","ipconfig /renew"],"contains_any",[],"Use 'ipconfig /release' then 'ipconfig /renew' to get a new DHCP lease.",["ipconfig with flags"]),
q("q-dhcp-04","dhcp","fundamentals","scenario","hard","DHCP clients on VLAN 10 can't get addresses from the DHCP server on VLAN 1. What's missing?",["dhcp relay","ip helper-address","relay agent","helper"],"contains_any",[],"DHCP broadcasts don't cross VLAN boundaries. Configure 'ip helper-address' (DHCP relay) on the VLAN 10 gateway interface.",["Broadcasts don't cross VLANs"]),
q("q-dhcp-05","dhcp","fundamentals","theory","medium","What is DHCP snooping?",["security","prevent rogue","trust","untrusted","validate"],"contains_any",[],"DHCP snooping is a security feature that validates DHCP messages and builds a binding table. It prevents rogue DHCP servers by only allowing DHCP offers from trusted ports.",["Security feature against rogue servers"]),
# ARP (5)
q("q-arp-01","arp-protocol","fundamentals","theory","easy","What does ARP resolve?",["ip to mac","ip address to mac address","layer 3 to layer 2","network to physical"],"contains_any",[],"ARP resolves IP addresses (Layer 3) to MAC addresses (Layer 2) on the local network.",["Maps between two address types"]),
q("q-arp-02","arp-protocol","fundamentals","command","medium","What command shows the ARP table on Linux?",["arp -a","ip neigh","ip neighbor"],"contains_any",[],"Use 'arp -a' or 'ip neigh show' to display the ARP cache on Linux.",["arp or ip command"]),
q("q-arp-03","arp-protocol","fundamentals","theory","medium","What is a gratuitous ARP?",["announce","unsolicited","own ip","update","duplicate detection"],"contains_any",[],"A gratuitous ARP is an unsolicited ARP reply announcing the sender's own IP-to-MAC mapping. Used for duplicate IP detection and updating caches after failover.",["ARP nobody asked for"]),
q("q-arp-04","arp-protocol","fundamentals","scenario","hard","You suspect ARP spoofing on your network. What tool and technique would you use to detect it?",["arpwatch","static arp","arp inspection","dai","duplicate"],"contains_any",[],"Use arpwatch to monitor ARP changes, enable Dynamic ARP Inspection (DAI) on switches, or look for duplicate IP-to-MAC mappings.",["Monitor for changes"]),
q("q-arp-05","arp-protocol","fundamentals","theory","medium","Why doesn't ARP work across routers?",["broadcast","local segment","layer 2","same subnet","not routed"],"contains_any",[],"ARP uses broadcast frames which are confined to the local Layer 2 segment. Routers don't forward broadcasts between interfaces.",["ARP uses broadcasts"]),
# NAT (5)
q("q-nat-01","nat-pat","fundamentals","theory","easy","What is the primary purpose of NAT?",["translate","private to public","conserve ip","address translation"],"contains_any",[],"NAT translates private IP addresses to public IP addresses, conserving the limited IPv4 address space.",["Address conservation"]),
q("q-nat-02","nat-pat","fundamentals","theory","medium","What is the difference between NAT and PAT?",["port","many to one","overload","multiple hosts one ip"],"contains_any",[],"NAT maps one IP to one IP. PAT (Port Address Translation/NAT overload) maps many private IPs to one public IP using different port numbers.",["PAT uses ports to distinguish"]),
q("q-nat-03","nat-pat","fundamentals","scenario","medium","An internal server needs to be accessible from the internet on port 443. What type of NAT do you configure?",["static nat","static","port forwarding","dnat"],"contains_any",[],"Use static NAT (or port forwarding/DNAT) to map a public IP:port to the internal server's private IP:port.",["One-to-one permanent mapping"]),
q("q-nat-04","nat-pat","fundamentals","theory","hard","What problems does NAT cause for IPsec VPN?",["esp","encapsulation","no port","nat-t","traversal"],"contains_any",[],"NAT breaks IPsec ESP because ESP doesn't have port numbers for PAT. NAT-Traversal (NAT-T) encapsulates ESP in UDP port 4500 to solve this.",["ESP has no ports"]),
q("q-nat-05","nat-pat","fundamentals","command","medium","On a Cisco router, what command enables PAT using the outside interface?",["ip nat inside source list","overload","ip nat"],"contains_any",[],"Use 'ip nat inside source list <ACL> interface <outside-if> overload' to enable PAT.",["overload keyword enables PAT"]),
# STP (5)
q("q-stp-01","stp-protocol","fundamentals","theory","easy","What is the purpose of Spanning Tree Protocol?",["prevent loops","loop prevention","loop-free","redundancy without loops"],"contains_any",[],"STP prevents Layer 2 loops by blocking redundant paths while maintaining backup links for failover.",["Loops are bad at Layer 2"]),
q("q-stp-02","stp-protocol","fundamentals","theory","medium","How is the root bridge elected in STP?",["lowest bridge id","lowest priority","bridge id","priority + mac"],"contains_any",[],"The switch with the lowest Bridge ID (priority + MAC address) becomes the root bridge. Default priority is 32768.",["Lowest wins"]),
q("q-stp-03","stp-protocol","fundamentals","theory","medium","What are the STP port states?",["blocking","listening","learning","forwarding","disabled"],"contains_any",[],"STP port states: Blocking → Listening → Learning → Forwarding (and Disabled). RSTP simplifies to: Discarding, Learning, Forwarding.",["Five states in classic STP"]),
q("q-stp-04","stp-protocol","fundamentals","scenario","hard","After a topology change, STP takes 50 seconds to converge. How can you reduce this?",["rstp","rapid spanning tree","portfast","802.1w"],"contains_any",[],"Use RSTP (802.1w) which converges in seconds instead of 50s. Also use PortFast on access ports to skip listening/learning.",["A faster version exists"]),
q("q-stp-05","stp-protocol","fundamentals","theory","medium","What is PortFast and when should it be used?",["access port","end device","skip states","immediately forwarding","host port"],"contains_any",[],"PortFast transitions a port immediately to forwarding state, skipping listening/learning. Use ONLY on access ports connected to end devices (not switches).",["Skip the wait on host ports"]),
# Wireless (5)
q("q-wifi-01","wireless-standards","fundamentals","theory","easy","What frequency bands does Wi-Fi 6 (802.11ax) use?",["2.4","5","2.4 and 5","both","dual band"],"contains_any",[],"Wi-Fi 6 (802.11ax) operates on both 2.4 GHz and 5 GHz bands.",["Dual band"]),
q("q-wifi-02","wireless-standards","fundamentals","theory","medium","What is the maximum theoretical speed of Wi-Fi 6?",["9.6 gbps","9.6","9608"],"contains_any",[],"Wi-Fi 6 has a maximum theoretical speed of 9.6 Gbps (with 8 spatial streams, 160 MHz channels).",["Almost 10 Gbps"]),
q("q-wifi-03","wireless-standards","fundamentals","theory","medium","What technology does Wi-Fi 6 use to serve multiple clients simultaneously?",["ofdma","mu-mimo","orthogonal frequency division multiple access"],"contains_any",[],"Wi-Fi 6 uses OFDMA (Orthogonal Frequency Division Multiple Access) and MU-MIMO to serve multiple clients simultaneously.",["Divides the channel into sub-carriers"]),
q("q-wifi-04","wireless-standards","fundamentals","theory","hard","What is the new frequency band introduced in Wi-Fi 6E?",["6 ghz","6ghz","6 GHz"],"contains_any",[],"Wi-Fi 6E extends into the 6 GHz band (5.925-7.125 GHz), providing 1200 MHz of additional spectrum.",["A new band above 5 GHz"]),
q("q-wifi-05","wireless-standards","fundamentals","scenario","medium","Users report slow WiFi in a dense office. What Wi-Fi 6 feature specifically addresses this?",["bss coloring","ofdma","target wake time","spatial reuse"],"contains_any",[],"BSS Coloring and OFDMA address dense environments. BSS Coloring reduces co-channel interference by marking frames from different BSSs.",["Designed for dense environments"]),
# Ethernet/IPv4/IPv6/misc (11)
q("q-eth-01","ethernet","fundamentals","theory","easy","What is the maximum frame size for standard Ethernet?",["1518","1518 bytes","1500 mtu"],"contains_any",[],"Standard Ethernet frame is max 1518 bytes (1500 byte payload + 18 byte header/trailer). Jumbo frames can be up to 9000 bytes.",["About 1500 for payload"]),
q("q-eth-02","ethernet","fundamentals","theory","medium","What is the difference between half-duplex and full-duplex Ethernet?",["simultaneous","both directions","send and receive","collision"],"contains_any",[],"Full-duplex allows simultaneous send and receive (no collisions). Half-duplex allows only one direction at a time (uses CSMA/CD).",["Can you talk and listen at the same time?"]),
q("q-ipv4-01","ipv4-addressing","fundamentals","theory","easy","What is the range of private IP addresses in Class A?",["10.0.0.0","10.0.0.0/8","10.x.x.x"],"contains_any",[],"Class A private range: 10.0.0.0 to 10.255.255.255 (10.0.0.0/8).",["Starts with 10"]),
q("q-ipv4-02","ipv4-addressing","fundamentals","command","medium","What is the CIDR notation for the Class B private range?",["172.16.0.0/12","/12"],"contains_any",[],"Class B private: 172.16.0.0/12 (172.16.0.0 to 172.31.255.255).",["172.16 to 172.31"]),
q("q-ipv6-01","ipv6-basics","fundamentals","theory","easy","How many bits are in an IPv6 address?",["128","128 bits"],"contains_any",[],"IPv6 addresses are 128 bits long (compared to 32 bits for IPv4).",["Four times IPv4"]),
q("q-ipv6-02","ipv6-basics","fundamentals","theory","medium","What is the IPv6 loopback address?",["::1"],"exact",[],"The IPv6 loopback address is ::1 (equivalent to 127.0.0.1 in IPv4).",["Very short"]),
q("q-ipv6-03","ipv6-basics","fundamentals","theory","medium","What does SLAAC stand for and what does it do?",["stateless address autoconfiguration","auto configure","automatic address"],"contains_any",[],"SLAAC (Stateless Address Autoconfiguration) allows IPv6 hosts to automatically configure their own addresses using router advertisements.",["Hosts configure themselves"]),
q("q-http-01","http-https","fundamentals","theory","easy","What port does HTTP use by default?",["80","port 80"],"contains_any",[],"HTTP uses TCP port 80 by default.",["A very common port"]),
q("q-ssh-01","ssh-protocol","fundamentals","theory","easy","What port does SSH use by default?",["22","port 22"],"contains_any",[],"SSH uses TCP port 22 by default.",["A well-known port"]),
q("q-ntp-01","ntp-protocol","fundamentals","theory","medium","What port and protocol does NTP use?",["123","udp 123","udp/123"],"contains_any",[],"NTP uses UDP port 123.",["UDP, not TCP"]),
q("q-icmp-01","icmp-protocol","fundamentals","theory","medium","What ICMP type and code indicates 'Destination Unreachable - Port Unreachable'?",["type 3 code 3","3/3","type 3, code 3"],"contains_any",[],"ICMP Type 3, Code 3 = Destination Unreachable, Port Unreachable. Sent when UDP port has no listener.",["Type 3 is unreachable"]),
]

if __name__ == "__main__":
    with open(OUTPUT, 'w') as f:
        json.dump(QS, f, indent=2)
    print(f"Generated {len(QS)} fundamentals questions → {OUTPUT.name}")
