#!/usr/bin/env python3
"""Generate quiz questions for Network Engineering domain (90 questions)."""
import json
from pathlib import Path
OUTPUT = Path(__file__).parent.parent / "data" / "questions" / "engineering_quiz.json"

def q(id,topic,domain,qtype,diff,question,answers,validation,keywords,explanation,hints):
    return {"id":id,"topic_id":topic,"domain":domain,"type":qtype,"difficulty":diff,
            "question":question,"correct_answers":answers,"validation_type":validation,
            "required_keywords":keywords,"explanation":explanation,"hints":hints}

QS = [
# OSPF (15)
q("q-ospf-01","ospf-fundamentals","network_engineering","theory","easy","What type of routing protocol is OSPF?",["link-state","link state"],"contains_any",[],"OSPF is a link-state routing protocol that builds a complete topology map of the network.",["Not distance-vector"]),
q("q-ospf-02","ospf-fundamentals","network_engineering","theory","medium","What is the OSPF administrative distance?",["110"],"exact",[],"OSPF has an administrative distance of 110 (lower than RIP's 120, higher than static routes' 1).",["Between 100 and 120"]),
q("q-ospf-03","ospf-fundamentals","network_engineering","theory","medium","What multicast address does OSPF use for all OSPF routers?",["224.0.0.5"],"exact",[],"OSPF uses 224.0.0.5 (AllSPFRouters) and 224.0.0.6 (AllDRouters).",["224.0.0.x range"]),
q("q-ospf-04","ospf-fundamentals","network_engineering","command","medium","What command shows OSPF neighbor relationships on Cisco?",["show ip ospf neighbor"],"contains_any",[],"Use 'show ip ospf neighbor' to verify OSPF adjacencies and their states.",["show ip ospf..."]),
q("q-ospf-05","ospf-fundamentals","network_engineering","theory","hard","What are the OSPF neighbor states in order?",["down init 2-way exstart exchange loading full","down, init, 2-way, exstart, exchange, loading, full"],"contains_any",[],"OSPF states: Down → Init → 2-Way → ExStart → Exchange → Loading → Full.",["Seven states"]),
q("q-ospf-06","ospf-fundamentals","network_engineering","theory","medium","What is the role of the OSPF Designated Router (DR)?",["reduce adjacencies","lsa flooding","represent segment","reduce overhead"],"contains_any",[],"The DR reduces OSPF overhead on multi-access networks by acting as the central point for LSA exchange, reducing the number of adjacencies from n*(n-1)/2 to n.",["Reduces the number of relationships needed"]),
q("q-ospf-07","ospf-fundamentals","network_engineering","scenario","hard","Two OSPF routers won't form an adjacency. What parameters must match?",["area","hello","dead","network type","authentication","subnet","mtu"],"contains_any",[],"OSPF adjacency requires matching: area ID, hello/dead timers, network type, authentication, subnet mask, and MTU.",["Several parameters must agree"]),
q("q-ospf-08","ospf-fundamentals","network_engineering","theory","medium","What is OSPF Area 0?",["backbone","backbone area","transit area"],"contains_any",[],"Area 0 is the backbone area. All other areas must connect to Area 0 (directly or via virtual links).",["The center of OSPF"]),
q("q-ospf-09","ospf-fundamentals","network_engineering","command","hard","What command summarizes OSPF routes at an ABR?",["area range","area 0 range"],"contains_any",[],"Use 'area <id> range <network> <mask>' on an ABR to summarize routes between areas.",["area ... range ..."]),
q("q-ospf-10","ospf-fundamentals","network_engineering","theory","medium","What LSA type does an ABR generate for inter-area routes?",["type 3","lsa type 3","summary lsa"],"contains_any",[],"ABRs generate Type 3 Summary LSAs to advertise routes between OSPF areas.",["Summary LSA"]),
q("q-ospf-11","ospf-fundamentals","network_engineering","theory","hard","What is an OSPF stub area?",["no external","no type 5","no asbr","default route"],"contains_any",[],"A stub area doesn't accept external (Type 5) LSAs. The ABR injects a default route instead, reducing the LSDB size.",["Blocks external routes"]),
q("q-ospf-12","ospf-fundamentals","network_engineering","command","medium","What is the default OSPF hello interval on a broadcast network?",["10","10 seconds"],"contains_any",[],"OSPF hello interval is 10 seconds on broadcast/point-to-point networks, 30 seconds on NBMA.",["A common timer value"]),
q("q-ospf-13","ospf-fundamentals","network_engineering","theory","medium","What metric does OSPF use?",["cost","bandwidth","reference bandwidth"],"contains_any",[],"OSPF uses cost as its metric, calculated as reference bandwidth / interface bandwidth. Default reference is 100 Mbps.",["Based on bandwidth"]),
q("q-ospf-14","ospf-fundamentals","network_engineering","scenario","hard","You have a 10 Gbps link but OSPF shows cost 1 (same as 100 Mbps). How do you fix this?",["auto-cost reference-bandwidth","reference bandwidth","change reference"],"contains_any",[],"Change reference bandwidth: 'auto-cost reference-bandwidth 10000' (in Mbps) so 10G gets cost 1 and 1G gets cost 10.",["The default reference is too low"]),
q("q-ospf-15","ospf-fundamentals","network_engineering","command","medium","What command enables OSPF on all interfaces in 10.0.0.0/8?",["network 10.0.0.0 0.255.255.255 area","router ospf","network 10.0.0.0"],"contains_any",[],"Under 'router ospf <process-id>', use 'network 10.0.0.0 0.255.255.255 area 0'.",["network command with wildcard"]),
# BGP (15)
q("q-bgp-01","bgp-fundamentals","network_engineering","theory","easy","What is the primary purpose of BGP?",["inter-as","between autonomous systems","internet routing","path vector"],"contains_any",[],"BGP is the inter-AS routing protocol that routes traffic between autonomous systems on the internet.",["The internet's routing protocol"]),
q("q-bgp-02","bgp-fundamentals","network_engineering","theory","medium","What TCP port does BGP use?",["179","port 179"],"contains_any",[],"BGP uses TCP port 179 for establishing peer sessions.",["A specific TCP port"]),
q("q-bgp-03","bgp-fundamentals","network_engineering","theory","medium","What is the difference between iBGP and eBGP?",["internal external","same as different as","within between"],"contains_any",[],"iBGP is between routers in the same AS. eBGP is between routers in different ASes. iBGP doesn't change next-hop by default.",["Internal vs External"]),
q("q-bgp-04","bgp-fundamentals","network_engineering","theory","hard","What is the BGP path selection order (first 4 attributes)?",["weight","local preference","local-pref","as-path","origin","med"],"contains_any",[],"BGP path selection: 1) Highest Weight (Cisco), 2) Highest Local Preference, 3) Shortest AS-Path, 4) Lowest Origin type (i>e>?).",["Weight, Local Pref, AS-Path, Origin"]),
q("q-bgp-05","bgp-fundamentals","network_engineering","command","medium","What command shows BGP neighbors on Cisco?",["show ip bgp summary","show bgp summary"],"contains_any",[],"Use 'show ip bgp summary' to see BGP peer status, AS numbers, and prefix counts.",["show ip bgp..."]),
q("q-bgp-06","bgp-fundamentals","network_engineering","theory","medium","What is AS-Path prepending used for?",["influence inbound","make path longer","less preferred","traffic engineering"],"contains_any",[],"AS-Path prepending makes a path appear longer to influence inbound traffic — neighbors prefer shorter AS-paths.",["Make your path look worse"]),
q("q-bgp-07","bgp-fundamentals","network_engineering","theory","hard","What is the BGP split-horizon rule for iBGP?",["not advertise to ibgp","learned from ibgp","route reflector","full mesh"],"contains_any",[],"iBGP split-horizon: routes learned from an iBGP peer are not advertised to other iBGP peers. Solved by full mesh, route reflectors, or confederations.",["iBGP doesn't re-advertise to iBGP"]),
q("q-bgp-08","bgp-fundamentals","network_engineering","theory","medium","What is a BGP route reflector?",["reduce full mesh","ibgp scalability","reflect routes","client"],"contains_any",[],"A route reflector re-advertises iBGP routes to other iBGP peers, eliminating the need for full mesh iBGP.",["Solves the full-mesh requirement"]),
q("q-bgp-09","bgp-fundamentals","network_engineering","scenario","hard","Your BGP peer is stuck in Active state. What are common causes?",["tcp connection","port 179","acl","firewall","reachability","authentication"],"contains_any",[],"Active state means BGP is trying to establish TCP connection. Check: IP reachability, port 179 not blocked by ACL/firewall, correct neighbor IP, authentication mismatch.",["Can't establish TCP"]),
q("q-bgp-10","bgp-fundamentals","network_engineering","theory","medium","What is the default BGP keepalive and hold timer?",["60","180","60 seconds","180 seconds"],"contains_any",[],"BGP default keepalive is 60 seconds, hold timer is 180 seconds (3x keepalive).",["Keepalive and 3x that"]),
q("q-bgp-11","bgp-fundamentals","network_engineering","command","hard","How do you filter BGP routes using a prefix-list on Cisco?",["ip prefix-list","neighbor prefix-list","prefix-list"],"contains_any",[],"Create 'ip prefix-list <name> permit/deny <prefix>/<len>' then apply with 'neighbor <ip> prefix-list <name> in/out'.",["ip prefix-list command"]),
q("q-bgp-12","bgp-fundamentals","network_engineering","theory","medium","What is BGP community and what is it used for?",["tag","label","group routes","policy","signal"],"contains_any",[],"BGP communities are tags attached to routes for policy signaling. Common: no-export, no-advertise, local-as.",["Tags for routes"]),
q("q-bgp-13","bgp-fundamentals","network_engineering","theory","hard","What is BGP graceful restart?",["maintain forwarding","restart without disruption","stale routes","preserve"],"contains_any",[],"Graceful restart allows a BGP router to restart without disrupting traffic. Peers maintain stale routes during restart, preserving forwarding.",["Keep forwarding during restart"]),
q("q-bgp-14","bgp-fundamentals","network_engineering","scenario","medium","You want to prefer one ISP over another for outbound traffic. What BGP attribute do you modify?",["local preference","local-pref","weight"],"contains_any",[],"Set higher Local Preference on routes from the preferred ISP. Local-pref is shared within the AS and higher is preferred.",["Higher is better for this attribute"]),
q("q-bgp-15","bgp-fundamentals","network_engineering","theory","medium","What is the BGP administrative distance for eBGP and iBGP?",["20","200","20 and 200"],"contains_any",[],"eBGP has AD 20 (very trusted), iBGP has AD 200 (less trusted than OSPF 110).",["eBGP is very trusted"]),
]

if __name__ == "__main__":
    with open(OUTPUT, 'w') as f:
        json.dump(QS, f, indent=2)
    print(f"Generated {len(QS)} engineering questions → {OUTPUT.name}")
