#!/usr/bin/env python3
"""Generate quiz questions for NOC, Security, Cloud, Automation domains."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "questions"

def q(id,topic,domain,qtype,diff,question,answers,validation,keywords,explanation,hints):
    return {"id":id,"topic_id":topic,"domain":domain,"type":qtype,"difficulty":diff,
            "question":question,"correct_answers":answers,"validation_type":validation,
            "required_keywords":keywords,"explanation":explanation,"hints":hints}

# ===================== NOC OPERATIONS (100) =====================
NOC = [
q("q-noc-alert-01","alerting-thresholds","noc_operations","theory","medium","What is the difference between a threshold-based and anomaly-based alert?",["static vs dynamic","fixed value vs baseline","deviation","normal behavior"],"contains_any",[],"Threshold alerts trigger at fixed values (CPU > 90%). Anomaly alerts detect deviations from learned baseline behavior.",["One is fixed, one learns"]),
q("q-noc-alert-02","alerting-thresholds","noc_operations","scenario","medium","CPU alerts fire every 5 minutes during batch jobs at 2 AM. How do you fix this?",["maintenance window","suppress","schedule","time-based","threshold adjustment"],"contains_any",[],"Configure maintenance windows or time-based alert suppression for known batch job schedules.",["Scheduled events shouldn't alert"]),
q("q-noc-alert-03","alerting-thresholds","noc_operations","theory","hard","What is alert fatigue and how do you prevent it?",["too many alerts","ignore","desensitize","tune","reduce noise"],"contains_any",[],"Alert fatigue occurs when operators receive too many alerts and start ignoring them. Prevent by tuning thresholds, deduplication, correlation, and severity classification.",["When everything alerts, nothing matters"]),
q("q-noc-incident-01","incident-mgmt","noc_operations","theory","easy","What are the typical incident severity levels?",["p1 p2 p3","critical major minor","sev 1 2 3","high medium low"],"contains_any",[],"Common severity levels: P1/Critical (service down), P2/Major (degraded), P3/Minor (limited impact), P4/Low (cosmetic).",["Usually 3-5 levels"]),
q("q-noc-incident-02","incident-mgmt","noc_operations","theory","medium","What is the first step in incident response?",["identify","detect","acknowledge","triage","assess"],"contains_any",[],"First step: Identify/Detect the incident, then Triage (assess severity and impact), then Respond.",["Before you can fix it, you must know about it"]),
q("q-noc-incident-03","incident-mgmt","noc_operations","scenario","hard","A P1 incident has been open for 30 minutes with no resolution. What should happen?",["escalate","escalation","management","next tier","communication"],"contains_any",[],"Escalate to next tier/management per escalation matrix. Increase communication frequency. Consider engaging vendor support.",["Time-based escalation"]),
q("q-noc-rca-01","rca-analysis","noc_operations","theory","medium","What is the '5 Whys' technique in RCA?",["ask why repeatedly","root cause","keep asking","underlying cause"],"contains_any",[],"The 5 Whys technique asks 'Why?' repeatedly (typically 5 times) to drill past symptoms to the root cause.",["Keep asking why"]),
q("q-noc-rca-02","rca-analysis","noc_operations","theory","medium","What is the difference between a root cause and a contributing factor?",["primary vs secondary","direct vs indirect","main cause","without it wouldn't happen"],"contains_any",[],"Root cause: the primary reason the incident occurred (removing it prevents recurrence). Contributing factors: conditions that made it worse but didn't directly cause it.",["One is the main reason"]),
q("q-noc-rca-03","rca-analysis","noc_operations","scenario","hard","A network outage was caused by a misconfigured ACL pushed during a change window. What is the root cause?",["insufficient review","no peer review","testing","change process","validation"],"contains_any",[],"Root cause is likely insufficient change validation/peer review process, not the ACL itself. The ACL is the immediate cause; the process gap is the root cause.",["Look beyond the technical error"]),
q("q-noc-sla-01","sla-mgmt","noc_operations","theory","medium","What does 99.99% availability (four nines) mean in downtime per year?",["52 minutes","52.6 minutes","less than an hour"],"contains_any",[],"99.99% = 52.6 minutes of allowed downtime per year (4.38 min/month).",["About an hour per year"]),
q("q-noc-sla-02","sla-mgmt","noc_operations","command","medium","How do you calculate availability percentage?",["uptime / total time","(total - downtime) / total","mtbf / (mtbf + mttr)"],"contains_any",[],"Availability = (Total Time - Downtime) / Total Time × 100%. Also: MTBF / (MTBF + MTTR).",["Uptime divided by total time"]),
q("q-noc-sla-03","sla-mgmt","noc_operations","theory","hard","What is the difference between MTBF and MTTR?",["between failures","time to repair","mean time","failure vs recovery"],"contains_any",[],"MTBF (Mean Time Between Failures) = average time between incidents. MTTR (Mean Time To Repair/Recover) = average time to restore service.",["One measures reliability, one measures recovery"]),
q("q-noc-snmp-01","snmp-monitoring","noc_operations","theory","easy","What port does SNMP use?",["161","udp 161"],"contains_any",[],"SNMP uses UDP port 161 for queries and UDP port 162 for traps.",["UDP, not TCP"]),
q("q-noc-snmp-02","snmp-monitoring","noc_operations","theory","medium","What is the difference between SNMP polling and traps?",["pull vs push","agent sends","manager queries","unsolicited"],"contains_any",[],"Polling: manager queries agents periodically (pull). Traps: agents send unsolicited notifications to manager (push).",["One asks, one tells"]),
q("q-noc-snmp-03","snmp-monitoring","noc_operations","theory","hard","Why is SNMPv3 preferred over v2c?",["authentication","encryption","security","no community string","privacy"],"contains_any",[],"SNMPv3 adds authentication (verify sender), encryption (privacy), and access control. v2c uses plaintext community strings.",["Security features"]),
q("q-noc-snmp-04","snmp-monitoring","noc_operations","command","medium","What is an OID in SNMP?",["object identifier","mib tree","numeric path","identify variable"],"contains_any",[],"An OID (Object Identifier) is a numeric path in the MIB tree that uniquely identifies a managed object (e.g., 1.3.6.1.2.1.1.1 = sysDescr).",["A numeric address in the MIB"]),
q("q-noc-syslog-01","syslog-monitoring","noc_operations","theory","easy","What are the syslog severity levels from most to least severe?",["emergency alert critical error warning notice info debug","0 1 2 3 4 5 6 7"],"contains_any",[],"Syslog severities: 0-Emergency, 1-Alert, 2-Critical, 3-Error, 4-Warning, 5-Notice, 6-Info, 7-Debug.",["8 levels, 0 is worst"]),
q("q-noc-syslog-02","syslog-monitoring","noc_operations","theory","medium","What port does syslog use by default?",["514","udp 514"],"contains_any",[],"Syslog uses UDP port 514 by default. Syslog over TLS uses TCP port 6514.",["UDP by default"]),
q("q-noc-netflow-01","netflow","noc_operations","theory","medium","What information does a NetFlow record contain?",["source ip","destination ip","port","protocol","bytes","packets"],"contains_any",[],"NetFlow records contain: source/dest IP, source/dest port, protocol, byte count, packet count, timestamps, and interface info.",["The 5-tuple plus more"]),
q("q-noc-netflow-02","netflow","noc_operations","scenario","hard","You need to identify which application is consuming the most bandwidth. What tool/protocol helps?",["netflow","sflow","ipfix","flow analysis"],"contains_any",[],"Use NetFlow/sFlow/IPFIX to analyze traffic flows by application (port), source, destination, and volume.",["Flow-based analysis"]),
q("q-noc-troubleshoot-01","network-troubleshooting","noc_operations","theory","easy","What is the first step in network troubleshooting methodology?",["identify","define problem","gather information","symptoms"],"contains_any",[],"Step 1: Identify/define the problem — gather symptoms, affected users, scope, and timeline.",["Understand what's wrong first"]),
q("q-noc-troubleshoot-02","network-troubleshooting","noc_operations","command","medium","What command tests Layer 3 connectivity to a remote host?",["ping","traceroute","tracert"],"contains_any",[],"Use ping to test basic IP connectivity (ICMP echo request/reply).",["The most basic connectivity test"]),
q("q-noc-troubleshoot-03","network-troubleshooting","noc_operations","command","medium","What command shows the path packets take to a destination?",["traceroute","tracert","mtr"],"contains_any",[],"traceroute (Linux) / tracert (Windows) shows each hop along the path using incrementing TTL values.",["Shows each router along the way"]),
q("q-noc-troubleshoot-04","network-troubleshooting","noc_operations","scenario","hard","Users report intermittent connectivity. Ping shows 5% packet loss. What do you check?",["interface errors","crc","duplex mismatch","cable","congestion","buffer"],"contains_any",[],"Check: interface error counters (CRC, collisions), duplex mismatch, cable issues, buffer overflows, QoS drops, and congestion.",["Look at interface statistics"]),
q("q-noc-capacity-01","capacity-planning","noc_operations","theory","medium","At what utilization percentage should you plan for bandwidth upgrades?",["70","80","70-80","threshold"],"contains_any",[],"Plan upgrades when sustained utilization reaches 70-80%. This leaves headroom for bursts and growth.",["Leave room for growth"]),
q("q-noc-grafana-01","grafana","noc_operations","theory","easy","What is Grafana primarily used for?",["visualization","dashboards","monitoring","graphs","metrics"],"contains_any",[],"Grafana is a visualization and dashboarding tool for time-series metrics from sources like Prometheus, InfluxDB, etc.",["Pretty graphs and dashboards"]),
q("q-noc-prometheus-01","prometheus","noc_operations","theory","medium","How does Prometheus collect metrics?",["pull","scrape","http","pull model"],"contains_any",[],"Prometheus uses a pull model — it scrapes metrics from HTTP endpoints exposed by targets at configured intervals.",["It goes and gets the data"]),
q("q-noc-prometheus-02","prometheus","noc_operations","command","medium","What query language does Prometheus use?",["promql"],"contains_any",[],"Prometheus uses PromQL (Prometheus Query Language) for querying time-series data.",["Prom..."]),
q("q-noc-zabbix-01","zabbix","noc_operations","theory","medium","What are the main components of a Zabbix deployment?",["server","agent","frontend","database","proxy"],"contains_any",[],"Zabbix has: Server (processes data), Agent (collects on hosts), Frontend (web UI), Database (stores data), and optional Proxy.",["Server, agent, and web interface"]),
q("q-noc-change-01","change-mgmt","noc_operations","theory","medium","What are the key elements of a change request?",["description","impact","rollback","schedule","approval","risk"],"contains_any",[],"Change request includes: description of change, business justification, risk assessment, impact analysis, rollback plan, schedule, and approvals.",["Plan for what could go wrong"]),
q("q-noc-change-02","change-mgmt","noc_operations","scenario","hard","A change caused an outage. The rollback plan doesn't work. What do you do?",["escalate","incident","bridge call","war room","vendor"],"contains_any",[],"Declare an incident, escalate immediately, open a bridge/war room, engage all relevant teams and vendors, communicate to stakeholders.",["This is now an incident"]),
q("q-noc-doc-01","documentation","noc_operations","theory","medium","What should a network runbook contain?",["procedures","steps","troubleshooting","escalation","contacts"],"contains_any",[],"Runbooks contain: step-by-step procedures, troubleshooting guides, escalation paths, contact lists, and decision trees for common scenarios.",["Step-by-step guides for operators"]),
q("q-noc-baseline-01","baselining","noc_operations","theory","medium","What is a network baseline and why is it important?",["normal behavior","reference","compare","deviation","typical"],"contains_any",[],"A baseline documents normal network behavior (bandwidth, latency, errors). It's the reference point for detecting anomalies and planning capacity.",["What does normal look like?"]),
]

# ===================== NETWORK SECURITY (100) =====================
SECURITY = [
q("q-sec-fw-01","firewall-fundamentals","network_security","theory","easy","What is the difference between a stateful and stateless firewall?",["track connections","state table","session","remember"],"contains_any",[],"Stateful firewalls track connection state (SYN, established, etc.) and allow return traffic automatically. Stateless firewalls evaluate each packet independently.",["One remembers, one doesn't"]),
q("q-sec-fw-02","firewall-fundamentals","network_security","theory","medium","What is the default firewall rule philosophy?",["deny all","implicit deny","default deny","block all"],"contains_any",[],"Default deny (implicit deny all) — block everything not explicitly permitted. This is the most secure approach.",["Block by default"]),
q("q-sec-fw-03","firewall-fundamentals","network_security","command","medium","In iptables, what command allows incoming SSH traffic?",["iptables -A INPUT -p tcp --dport 22 -j ACCEPT","INPUT","dport 22","ACCEPT"],"contains_any",[],"Use 'iptables -A INPUT -p tcp --dport 22 -j ACCEPT' to allow inbound SSH.",["INPUT chain, port 22, ACCEPT"]),
q("q-sec-fw-04","firewall-fundamentals","network_security","scenario","hard","You need to allow internal users to browse the web but block incoming connections. What firewall approach?",["stateful","allow established","outbound allow","return traffic"],"contains_any",[],"Use stateful inspection: allow outbound HTTP/HTTPS, and the stateful engine automatically allows return traffic. Block all unsolicited inbound.",["Allow out, track state"]),
q("q-sec-ids-01","ids-ips","network_security","theory","easy","What is the difference between IDS and IPS?",["detect vs prevent","inline vs passive","block vs alert","monitor vs stop"],"contains_any",[],"IDS detects and alerts (passive/out-of-band). IPS detects and blocks (inline, can drop packets).",["One watches, one acts"]),
q("q-sec-ids-02","ids-ips","network_security","theory","medium","What is the difference between signature-based and anomaly-based detection?",["known vs unknown","pattern vs baseline","signature vs behavior","database vs learning"],"contains_any",[],"Signature-based matches known attack patterns (fast, no false positives for known attacks). Anomaly-based detects deviations from normal (catches unknown attacks, more false positives).",["Known patterns vs learned behavior"]),
q("q-sec-ids-03","ids-ips","network_security","scenario","hard","Your IPS is dropping legitimate traffic (false positives). How do you address this?",["tune","whitelist","exception","threshold","sensitivity"],"contains_any",[],"Tune IPS rules: create exceptions for known-good traffic, adjust sensitivity thresholds, whitelist trusted sources, and move problematic rules to alert-only mode.",["Adjust sensitivity"]),
q("q-sec-vpn-01","vpn-ipsec","network_security","theory","medium","What are the two modes of IPsec?",["transport","tunnel","transport mode","tunnel mode"],"contains_any",[],"Transport mode: encrypts only payload (host-to-host). Tunnel mode: encrypts entire original packet and adds new IP header (site-to-site VPN).",["One encrypts payload, one encrypts everything"]),
q("q-sec-vpn-02","vpn-ipsec","network_security","theory","medium","What is the difference between ESP and AH in IPsec?",["encryption","authentication only","esp encrypts","ah authenticates"],"contains_any",[],"ESP provides encryption + authentication. AH provides authentication only (no encryption). ESP is used in almost all modern deployments.",["One encrypts, one only authenticates"]),
q("q-sec-vpn-03","vpn-ipsec","network_security","theory","hard","What are IKE Phase 1 and Phase 2?",["sa","security association","isakmp","ipsec sa","management","data"],"contains_any",[],"Phase 1 (ISAKMP SA): authenticates peers and establishes encrypted management tunnel. Phase 2 (IPsec SA): negotiates encryption for actual data traffic.",["Two phases: management then data"]),
q("q-sec-zt-01","zero-trust","network_security","theory","medium","What is the core principle of Zero Trust?",["never trust always verify","verify explicitly","no implicit trust","assume breach"],"contains_any",[],"Zero Trust: Never trust, always verify. No implicit trust based on network location. Verify every access request regardless of source.",["Trust nothing by default"]),
q("q-sec-zt-02","zero-trust","network_security","theory","hard","What are the key pillars of a Zero Trust architecture?",["identity","device","network","application","data","visibility"],"contains_any",[],"Zero Trust pillars: Identity verification, Device health, Network segmentation, Application access, Data protection, and Visibility/Analytics.",["Multiple pillars, not just network"]),
q("q-sec-seg-01","network-segmentation","network_security","theory","medium","What is network segmentation and why is it important?",["divide","isolate","separate","limit blast radius","contain"],"contains_any",[],"Network segmentation divides the network into isolated zones to limit lateral movement, contain breaches, and enforce access policies between segments.",["Divide and conquer"]),
q("q-sec-seg-02","network-segmentation","network_security","scenario","hard","An attacker compromised a workstation. How does proper segmentation limit damage?",["can't reach servers","lateral movement blocked","firewall between","acl","different vlan"],"contains_any",[],"Segmentation prevents the attacker from reaching servers/critical systems directly. Firewalls/ACLs between segments block unauthorized lateral movement.",["Walls between zones"]),
q("q-sec-ddos-01","ddos","network_security","theory","medium","What are the three main categories of DDoS attacks?",["volumetric","protocol","application","layer 3","layer 4","layer 7"],"contains_any",[],"DDoS categories: Volumetric (flood bandwidth), Protocol (exploit protocol weaknesses like SYN flood), Application (target L7 like HTTP floods).",["Three layers of attack"]),
q("q-sec-ddos-02","ddos","network_security","scenario","hard","Your web server is under a SYN flood attack. What immediate mitigation steps do you take?",["syn cookies","rate limit","blackhole","scrubbing","increase backlog"],"contains_any",[],"Enable SYN cookies, increase TCP backlog queue, implement rate limiting, engage DDoS scrubbing service, or blackhole the attack traffic.",["Multiple defenses needed"]),
q("q-sec-tls-01","tls-security","network_security","theory","medium","What is the minimum TLS version considered secure today?",["1.2","tls 1.2","1.3","tls 1.3"],"contains_any",[],"TLS 1.2 is the minimum acceptable version. TLS 1.3 is preferred. TLS 1.0 and 1.1 are deprecated.",["1.0 and 1.1 are dead"]),
q("q-sec-tls-02","tls-security","network_security","theory","hard","What is Perfect Forward Secrecy (PFS) and why does it matter?",["ephemeral","session key","compromise","past sessions","dhe","ecdhe"],"contains_any",[],"PFS uses ephemeral keys (DHE/ECDHE) so compromising the server's private key doesn't decrypt past sessions. Each session has unique keys.",["Past sessions stay safe"]),
q("q-sec-dns-01","dns-security","network_security","theory","medium","What is DNS poisoning/spoofing?",["fake response","wrong ip","redirect","malicious answer","cache"],"contains_any",[],"DNS poisoning injects false DNS responses into a resolver's cache, redirecting users to malicious servers.",["Fake DNS answers"]),
q("q-sec-dns-02","dns-security","network_security","theory","hard","How does DNSSEC prevent DNS spoofing?",["digital signature","sign","verify","authenticate","chain of trust"],"contains_any",[],"DNSSEC adds digital signatures to DNS records. Resolvers verify signatures using a chain of trust from the root, ensuring responses are authentic.",["Cryptographic signatures on DNS"]),
q("q-sec-nac-01","nac","network_security","theory","medium","What is Network Access Control (NAC)?",["authenticate before access","device compliance","posture check","admission"],"contains_any",[],"NAC authenticates devices and checks their security posture (patches, AV, compliance) before granting network access.",["Check before you connect"]),
q("q-sec-802-01","802-1x","network_security","theory","medium","What are the three roles in 802.1X authentication?",["supplicant authenticator server","client switch radius","supplicant, authenticator, authentication server"],"contains_any",[],"802.1X roles: Supplicant (client), Authenticator (switch/AP), Authentication Server (RADIUS).",["Three parties involved"]),
q("q-sec-wireless-01","wireless-security","network_security","theory","medium","What is the most secure WiFi authentication for enterprise?",["wpa3 enterprise","wpa2 enterprise","802.1x","eap-tls"],"contains_any",[],"WPA3-Enterprise with EAP-TLS (certificate-based) is the most secure. WPA2-Enterprise with 802.1X is also acceptable.",["Enterprise mode with certificates"]),
q("q-sec-wireless-02","wireless-security","network_security","theory","hard","What is a rogue access point and how do you detect it?",["unauthorized ap","wids","wireless ids","scanning","unauthorized"],"contains_any",[],"A rogue AP is an unauthorized access point on your network. Detect with WIDS (Wireless IDS), periodic scanning, and NAC that blocks unknown devices.",["Unauthorized wireless"]),
q("q-sec-packet-01","packet-analysis","network_security","command","medium","What Wireshark display filter shows only HTTP POST requests?",["http.request.method == POST","http.request.method==POST","http.request.method == \"POST\""],"contains_any",[],"Use 'http.request.method == POST' to filter for HTTP POST requests in Wireshark.",["http.request.method"]),
q("q-sec-packet-02","packet-analysis","network_security","command","medium","What tcpdump command captures traffic on port 443?",["tcpdump -i","port 443","tcpdump port 443"],"contains_any",[],"Use 'tcpdump -i <interface> port 443' to capture HTTPS traffic.",["tcpdump with port filter"]),
q("q-sec-siem-01","siem","network_security","theory","medium","What is a SIEM and what does it do?",["security information event management","correlate","log","alert","centralize"],"contains_any",[],"SIEM (Security Information and Event Management) centralizes logs, correlates events, detects threats, and generates alerts.",["Centralize and correlate security data"]),
q("q-sec-siem-02","siem","network_security","theory","hard","What is the difference between a SIEM rule and a SIEM correlation?",["single event vs multiple","pattern","combine","sequence","multiple sources"],"contains_any",[],"A rule triggers on a single event type. Correlation combines multiple events across sources/time to detect complex attack patterns.",["One event vs pattern of events"]),
q("q-sec-microseg-01","microseg","network_security","theory","hard","What is microsegmentation and how does it differ from traditional segmentation?",["workload level","application","granular","east-west","per-vm"],"contains_any",[],"Microsegmentation applies security policies at the workload/application level (per-VM, per-container) rather than at network boundaries. Controls east-west traffic.",["More granular than VLANs"]),
]

# ===================== CLOUD NETWORKING (80) =====================
CLOUD = [
q("q-cloud-vpc-01","aws-vpc","cloud_networking","theory","easy","What is a VPC?",["virtual private cloud","isolated network","virtual network","private network in cloud"],"contains_any",[],"A VPC (Virtual Private Cloud) is an isolated virtual network in the cloud where you launch resources with your own IP addressing.",["Your own network in the cloud"]),
q("q-cloud-vpc-02","aws-vpc","cloud_networking","theory","medium","What is the difference between a public and private subnet in AWS?",["internet gateway","route to igw","public ip","no internet"],"contains_any",[],"Public subnet has a route to an Internet Gateway (IGW) and instances can have public IPs. Private subnet has no direct internet route.",["One has internet access"]),
q("q-cloud-vpc-03","aws-vpc","cloud_networking","command","medium","What is the maximum CIDR block size for an AWS VPC?",["16","/16"],"contains_any",[],"AWS VPC supports CIDR blocks from /16 (65,536 IPs) to /28 (16 IPs).",["Largest is /16"]),
q("q-cloud-sg-01","aws-security-groups","cloud_networking","theory","medium","How do AWS Security Groups differ from NACLs?",["stateful","stateless","instance level","subnet level","allow only"],"contains_any",[],"Security Groups are stateful (return traffic auto-allowed), instance-level, allow-only rules. NACLs are stateless, subnet-level, support allow and deny.",["One is stateful, one is stateless"]),
q("q-cloud-sg-02","aws-security-groups","cloud_networking","theory","medium","What is the default behavior of an AWS Security Group?",["deny all inbound","allow all outbound","implicit deny"],"contains_any",[],"Default: deny all inbound, allow all outbound. You add rules to allow specific inbound traffic.",["Deny in, allow out"]),
q("q-cloud-nacl-01","nacl","cloud_networking","theory","medium","What is the rule evaluation order for NACLs?",["lowest number first","numbered order","sequential","first match"],"contains_any",[],"NACL rules are evaluated in order from lowest rule number to highest. First matching rule is applied.",["Number order matters"]),
q("q-cloud-nacl-02","nacl","cloud_networking","scenario","hard","You added a NACL deny rule for port 22 (rule 50) but SSH still works. Why?",["lower number allow","rule before","earlier rule","rule number"],"contains_any",[],"A lower-numbered rule (e.g., rule 10 allowing all traffic) is evaluated first and matches before rule 50.",["Check for earlier matching rules"]),
q("q-cloud-rt-01","aws-route-tables","cloud_networking","theory","medium","What is the most specific route that wins in a route table?",["longest prefix","most specific","/32","longest match"],"contains_any",[],"Longest prefix match wins. A /32 route is more specific than /24, which is more specific than /16.",["More specific = longer prefix"]),
q("q-cloud-peer-01","vpc-peering-topic","cloud_networking","theory","medium","What is VPC peering?",["connect two vpcs","private connection","direct link between vpcs"],"contains_any",[],"VPC peering creates a private network connection between two VPCs, allowing resources to communicate using private IPs.",["Connect two VPCs privately"]),
q("q-cloud-peer-02","vpc-peering-topic","cloud_networking","theory","hard","What is a limitation of VPC peering?",["not transitive","no transit","can't route through","hub and spoke"],"contains_any",[],"VPC peering is NOT transitive. If VPC-A peers with VPC-B and VPC-B peers with VPC-C, A cannot reach C through B.",["Not transitive"]),
q("q-cloud-tgw-01","transit-gw","cloud_networking","theory","medium","What problem does AWS Transit Gateway solve?",["full mesh","scalability","many vpcs","hub","centralize"],"contains_any",[],"Transit Gateway eliminates the need for full-mesh VPC peering. It acts as a hub that all VPCs and on-premises networks connect to.",["Hub instead of full mesh"]),
q("q-cloud-dc-01","direct-connect","cloud_networking","theory","medium","What is AWS Direct Connect?",["dedicated connection","private link","not internet","physical connection"],"contains_any",[],"Direct Connect provides a dedicated private network connection from on-premises to AWS, bypassing the public internet for better performance and security.",["Private physical connection"]),
q("q-cloud-dc-02","direct-connect","cloud_networking","theory","hard","What is the difference between a Direct Connect and a VPN connection?",["dedicated vs internet","physical vs tunnel","consistent vs variable","bandwidth"],"contains_any",[],"Direct Connect: dedicated physical connection, consistent performance, higher bandwidth. VPN: encrypted tunnel over internet, variable performance, quick to set up.",["Physical vs logical"]),
q("q-cloud-hybrid-01","hybrid-connectivity","cloud_networking","scenario","hard","You need redundant connectivity to AWS with sub-10ms latency. What do you recommend?",["direct connect","dual direct connect","redundant dx","two connections"],"contains_any",[],"Use dual Direct Connect connections (ideally to different DX locations) for redundancy with consistent low latency.",["Dedicated connections for low latency"]),
q("q-cloud-lb-01","cloud-lb","cloud_networking","theory","medium","What are the types of load balancers in AWS?",["alb","nlb","application","network","gateway","clb"],"contains_any",[],"AWS has: ALB (Application/Layer 7), NLB (Network/Layer 4), GLB (Gateway/Layer 3), and Classic LB (legacy).",["Different layers"]),
q("q-cloud-lb-02","cloud-lb","cloud_networking","theory","medium","When would you use an NLB instead of an ALB?",["tcp","udp","low latency","millions","static ip","layer 4"],"contains_any",[],"Use NLB for: TCP/UDP traffic, ultra-low latency, millions of requests/sec, static IPs, or non-HTTP protocols.",["Layer 4, high performance"]),
q("q-cloud-dns-01","cloud-dns2","cloud_networking","theory","medium","What is AWS Route 53?",["dns service","domain name","routing","hosted zones"],"contains_any",[],"Route 53 is AWS's DNS service providing domain registration, DNS routing, and health checking.",["AWS DNS"]),
q("q-cloud-cdn-01","cdn","cloud_networking","theory","medium","What is a CDN and how does it improve performance?",["content delivery","edge","cache","closer to user","distribute"],"contains_any",[],"A CDN caches content at edge locations worldwide, serving users from the nearest location to reduce latency and offload origin servers.",["Closer to users"]),
q("q-cloud-container-01","container-net","cloud_networking","theory","hard","How does Kubernetes networking differ from traditional networking?",["flat network","pod ip","every pod addressable","no nat between pods","overlay"],"contains_any",[],"Kubernetes requires: every pod gets a unique IP, pods can communicate without NAT, and the network is flat (all pods can reach all pods by default).",["Every pod gets an IP"]),
q("q-cloud-k8s-01","kubernetes-networking","cloud_networking","theory","medium","What is a Kubernetes Service of type ClusterIP?",["internal only","cluster internal","virtual ip","not external"],"contains_any",[],"ClusterIP exposes the service on an internal IP only accessible within the cluster. It's the default Service type.",["Internal only"]),
q("q-cloud-k8s-02","kubernetes-networking","cloud_networking","theory","medium","What is a Kubernetes Ingress?",["http routing","layer 7","path-based","host-based","external http"],"contains_any",[],"Ingress manages external HTTP/HTTPS access to services, providing path-based and host-based routing, TLS termination.",["HTTP routing from outside"]),
q("q-cloud-azure-01","azure-vnet","cloud_networking","theory","medium","What is the Azure equivalent of AWS VPC?",["vnet","virtual network"],"contains_any",[],"Azure Virtual Network (VNet) is the equivalent of AWS VPC — an isolated network for Azure resources.",["VNet"]),
q("q-cloud-private-01","private-ep","cloud_networking","theory","hard","What is a VPC endpoint (AWS) or Private Link?",["private access","no internet","service without igw","private connection to service"],"contains_any",[],"VPC endpoints allow private access to AWS services (S3, DynamoDB, etc.) without traversing the internet or requiring an IGW/NAT.",["Access services privately"]),
q("q-cloud-waf-01","cloud-waf2","cloud_networking","theory","medium","What does a Web Application Firewall (WAF) protect against?",["sql injection","xss","owasp","layer 7","application attacks"],"contains_any",[],"WAF protects against application-layer attacks: SQL injection, XSS, CSRF, and other OWASP Top 10 vulnerabilities.",["Application-layer attacks"]),
q("q-cloud-mesh-01","service-mesh2","cloud_networking","theory","hard","What is a service mesh and what problem does it solve?",["service-to-service","sidecar","observability","traffic management","istio","envoy"],"contains_any",[],"A service mesh manages service-to-service communication using sidecar proxies. Provides: traffic management, observability, security (mTLS), and resilience without code changes.",["Manages microservice communication"]),
]

# ===================== NETWORK AUTOMATION (80) =====================
AUTOMATION = [
q("q-auto-ansible-01","ansible-network","network_automation","theory","easy","What is Ansible and why is it popular for network automation?",["agentless","ssh","yaml","playbook","no agent"],"contains_any",[],"Ansible is agentless (uses SSH/NETCONF), uses YAML playbooks, and has extensive network modules. No software needed on network devices.",["No agent required"]),
q("q-auto-ansible-02","ansible-network","network_automation","command","medium","What is the basic structure of an Ansible playbook?",["hosts","tasks","name","module","play"],"contains_any",[],"A playbook contains plays with: hosts (targets), tasks (actions using modules), and optional vars, handlers, roles.",["Hosts and tasks"]),
q("q-auto-ansible-03","ansible-network","network_automation","command","medium","What Ansible module configures Cisco IOS devices?",["ios_config","cisco.ios.ios_config","ios_command"],"contains_any",[],"Use cisco.ios.ios_config for configuration changes and cisco.ios.ios_command for show commands.",["ios_config or ios_command"]),
q("q-auto-ansible-04","ansible-network","network_automation","scenario","hard","You need to push the same VLAN config to 500 switches. What Ansible feature helps?",["inventory","group","loop","template","jinja2","role"],"contains_any",[],"Use inventory groups, Jinja2 templates for device-specific configs, and roles for reusable automation. Ansible handles parallel execution.",["Groups and templates"]),
q("q-auto-terraform-01","terraform-network","network_automation","theory","medium","What is Terraform and what approach does it use?",["infrastructure as code","declarative","state","provider","iac"],"contains_any",[],"Terraform is a declarative IaC tool. You define desired state, Terraform calculates and applies changes. Uses providers for different platforms.",["Declare what you want, not how"]),
q("q-auto-terraform-02","terraform-network","network_automation","theory","medium","What is Terraform state and why is it important?",["track resources","current state","mapping","drift detection"],"contains_any",[],"Terraform state maps your config to real resources. It tracks what exists, detects drift, and determines what changes are needed.",["Tracks what's deployed"]),
q("q-auto-terraform-03","terraform-network","network_automation","command","medium","What command applies Terraform changes?",["terraform apply"],"contains_any",[],"'terraform apply' executes the planned changes to reach the desired state.",["terraform ..."]),
q("q-auto-netmiko-01","python-netmiko","network_automation","theory","medium","What is Netmiko?",["python ssh","multi-vendor","network device","simplify paramiko"],"contains_any",[],"Netmiko is a Python library that simplifies SSH connections to network devices. Supports multi-vendor (Cisco, Juniper, Arista, etc.).",["Python SSH for network devices"]),
q("q-auto-netmiko-02","python-netmiko","network_automation","command","medium","What Netmiko method sends configuration commands?",["send_config_set","send_config"],"contains_any",[],"Use net_connect.send_config_set(['commands']) to push configuration commands to a device.",["send_config_..."]),
q("q-auto-netmiko-03","python-netmiko","network_automation","command","hard","Write a basic Netmiko connection dictionary for a Cisco switch.",["device_type","host","username","password","cisco_ios"],"contains_all",[],"device = {'device_type': 'cisco_ios', 'host': '10.0.0.1', 'username': 'admin', 'password': 'pass'}",["Four required keys"]),
q("q-auto-netconf-01","netconf-yang","network_automation","theory","medium","What is NETCONF and what port does it use?",["830","network configuration","xml","rpc","yang"],"contains_any",[],"NETCONF is a network management protocol using XML/RPC over SSH (port 830). It uses YANG data models for structured configuration.",["XML-based, port 830"]),
q("q-auto-netconf-02","netconf-yang","network_automation","theory","hard","What is YANG?",["data model","schema","structure","define configuration","modeling language"],"contains_any",[],"YANG is a data modeling language that defines the structure of configuration and operational data for NETCONF/RESTCONF.",["Defines the data structure"]),
q("q-auto-restapi-01","rest-api-network","network_automation","theory","medium","What HTTP methods are used in RESTful APIs for CRUD operations?",["get post put delete","get","post","put","delete"],"contains_any",[],"REST CRUD: GET (Read), POST (Create), PUT (Update/Replace), PATCH (Partial Update), DELETE (Remove).",["HTTP verbs"]),
q("q-auto-restapi-02","rest-api-network","network_automation","theory","medium","What is the difference between PUT and PATCH?",["full replace vs partial","entire vs partial","complete vs subset"],"contains_any",[],"PUT replaces the entire resource. PATCH modifies only specified fields. PATCH is more efficient for small changes.",["Full vs partial update"]),
q("q-auto-jinja-01","jinja2","network_automation","theory","medium","What is Jinja2 used for in network automation?",["template","config generation","variable substitution","dynamic config"],"contains_any",[],"Jinja2 is a templating engine that generates device-specific configurations from templates + variables. Used with Ansible, Python, etc.",["Templates with variables"]),
q("q-auto-jinja-02","jinja2","network_automation","command","medium","What syntax does Jinja2 use for variables?",["{{ }}","double curly","{{ variable }}"],"contains_any",[],"Jinja2 uses {{ variable }} for variable substitution and {% %} for logic (loops, conditions).",["Double curly braces"]),
q("q-auto-git-01","git-configs","network_automation","theory","medium","Why should network configurations be stored in Git?",["version control","history","rollback","audit","change tracking"],"contains_any",[],"Git provides: version history, change tracking, rollback capability, audit trail, collaboration, and CI/CD integration for network configs.",["Track changes over time"]),
q("q-auto-git-02","git-configs","network_automation","command","easy","What Git command shows the history of changes?",["git log"],"contains_any",[],"'git log' shows commit history with authors, dates, and messages.",["git ..."]),
q("q-auto-cicd-01","cicd-network","network_automation","theory","hard","What does a CI/CD pipeline for network changes look like?",["lint","test","validate","deploy","approve","staging"],"contains_any",[],"Network CI/CD: Lint configs → Validate syntax → Test in lab/simulation → Peer review → Approve → Deploy to staging → Deploy to production.",["Multiple validation stages"]),
q("q-auto-cicd-02","cicd-network","network_automation","theory","medium","What is the benefit of CI/CD for network changes?",["automated testing","consistency","reduce errors","repeatable","validation"],"contains_any",[],"CI/CD ensures: automated validation before deployment, consistent process, reduced human errors, audit trail, and easy rollback.",["Automated validation"]),
q("q-auto-napalm-01","napalm","network_automation","theory","medium","What is NAPALM in network automation?",["network automation","multi-vendor","abstraction","get facts","config management"],"contains_any",[],"NAPALM (Network Automation and Programmability Abstraction Layer with Multivendor support) provides a unified API for multi-vendor network device management.",["Unified multi-vendor API"]),
q("q-auto-napalm-02","napalm","network_automation","theory","hard","What is NAPALM's 'compare_config' feature?",["diff","difference","candidate vs running","show changes","before apply"],"contains_any",[],"compare_config() shows the diff between candidate and running configuration before committing — like a dry-run for network changes.",["See changes before applying"]),
q("q-auto-nornir-01","nornir","network_automation","theory","medium","What is Nornir and how does it differ from Ansible?",["python framework","code not yaml","programmatic","threading","python native"],"contains_any",[],"Nornir is a Python automation framework. Unlike Ansible (YAML), Nornir uses pure Python, giving more flexibility and better performance with threading.",["Python-native, not YAML"]),
q("q-auto-scapy-01","python-scapy","network_automation","theory","medium","What is Scapy used for?",["packet crafting","packet manipulation","custom packets","protocol testing"],"contains_any",[],"Scapy is a Python library for crafting, sending, and analyzing network packets. Used for testing, scanning, and protocol development.",["Craft custom packets"]),
q("q-auto-testing-01","infra-testing","network_automation","theory","hard","What is Batfish and what does it do?",["config analysis","offline","network verification","pre-deployment","simulation"],"contains_any",[],"Batfish analyzes network configurations offline to verify correctness, find bugs, and test changes before deployment — without touching live devices.",["Analyze configs without deploying"]),
q("q-auto-sot-01","sot","network_automation","theory","medium","What is a Source of Truth (SoT) in network automation?",["single source","authoritative","intended state","netbox","database"],"contains_any",[],"A Source of Truth is the authoritative database defining the intended network state. Tools like NetBox serve as SoT for IP addresses, devices, and configurations.",["The authoritative record"]),
]

if __name__ == "__main__":
    # Save NOC questions
    with open(OUTPUT_DIR / "noc_quiz.json", 'w') as f:
        json.dump(NOC, f, indent=2)
    print(f"NOC: {len(NOC)} questions")

    # Save Security questions
    with open(OUTPUT_DIR / "security_quiz.json", 'w') as f:
        json.dump(SECURITY, f, indent=2)
    print(f"Security: {len(SECURITY)} questions")

    # Save Cloud questions
    with open(OUTPUT_DIR / "cloud_quiz.json", 'w') as f:
        json.dump(CLOUD, f, indent=2)
    print(f"Cloud: {len(CLOUD)} questions")

    # Save Automation questions
    with open(OUTPUT_DIR / "automation_quiz.json", 'w') as f:
        json.dump(AUTOMATION, f, indent=2)
    print(f"Automation: {len(AUTOMATION)} questions")

    # Count total
    total = 0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            total += len(json.load(f))
    print(f"\nTOTAL QUESTIONS: {total}")
