#!/usr/bin/env python3
"""Final push to 400+ questions."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "questions"

def q(id,topic,domain,qtype,diff,question,answers,validation,keywords,explanation,hints):
    return {"id":id,"topic_id":topic,"domain":domain,"type":qtype,"difficulty":diff,
            "question":question,"correct_answers":answers,"validation_type":validation,
            "required_keywords":keywords,"explanation":explanation,"hints":hints}

FINAL = [
q("q-fin-ospf-16","ospf-fundamentals","network_engineering","scenario","hard","OSPF neighbors are stuck in ExStart state. What is the likely cause?",["mtu mismatch","mtu","dbdescription","packet size"],"contains_any",[],"ExStart/Exchange stuck usually means MTU mismatch — DBD packets are too large for one side. Verify MTU matches on both ends.",["Packet size issue"]),
q("q-fin-bgp-16","bgp-fundamentals","network_engineering","theory","hard","What is BGP dampening?",["suppress flapping","penalty","route instability","suppress unstable"],"contains_any",[],"BGP dampening suppresses routes that flap (go up/down repeatedly) by assigning penalties. Prevents instability from propagating.",["Punish unstable routes"]),
q("q-fin-fw-07","firewall-fundamentals","network_security","command","medium","What is the default action in a Cisco ACL if no rule matches?",["implicit deny","deny all","drop","deny any"],"contains_any",[],"Every Cisco ACL has an implicit 'deny any' at the end. If no rule matches, traffic is dropped.",["Hidden deny at the end"]),
q("q-fin-sub-11","subnetting","fundamentals","command","hard","What is the valid host range for 10.10.10.0/30?",["10.10.10.1 to 10.10.10.2","10.10.10.1","10.10.10.2","10.10.10.1-10.10.10.2"],"contains_any",[],"A /30 has 2 usable hosts: .1 and .2 (network=.0, broadcast=.3).",["Only 2 usable in a /30"]),
q("q-fin-tcp-09","tcp-protocol","fundamentals","theory","hard","What is TCP Fast Open (TFO)?",["data in syn","reduce latency","first packet","cookie","0-rtt"],"contains_any",[],"TCP Fast Open allows data in the SYN packet (using a cookie from previous connection), reducing latency by one RTT for repeat connections.",["Send data immediately"]),
q("q-fin-vlan-09","vlans","fundamentals","command","hard","What is a voice VLAN and why is it used?",["separate voice traffic","qos","phone","ip phone","auxiliary"],"contains_any",[],"Voice VLAN separates IP phone traffic from data traffic on the same port, enabling QoS prioritization for voice without complex configs.",["Separate phone traffic"]),
q("q-fin-noc-cap-03","capacity-planning","noc_operations","scenario","hard","Your 1 Gbps WAN link hits 85% during business hours. What's your recommendation?",["upgrade","10g","bandwidth increase","plan upgrade","before saturation"],"contains_any",[],"Recommend upgrading to 10G (or adding a second link). At 85% sustained, bursts will cause drops. Plan upgrade before hitting 95%+.",["Too close to capacity"]),
q("q-fin-noc-prom-04","prometheus","noc_operations","command","hard","What PromQL function calculates the increase in a counter over time?",["increase(","increase"],"contains_any",[],"increase(counter[time]) calculates the total increase of a counter over the specified time window.",["Total growth over time"]),
q("q-fin-sec-fw-08","firewall-fundamentals","network_security","theory","hard","What is a DMZ and what goes in it?",["demilitarized zone","between internal external","public-facing","web servers","buffer"],"contains_any",[],"DMZ is a network segment between internal and external networks. Hosts public-facing services (web, mail, DNS) that need internet access but shouldn't be on the internal network.",["Buffer zone for public services"]),
q("q-fin-sec-vpn-06","vpn-ipsec","network_security","scenario","medium","Users report VPN disconnects when switching from WiFi to mobile data. What feature helps?",["mobike","ikev2 mobike","mobility","reconnect"],"contains_any",[],"IKEv2 MOBIKE allows VPN sessions to survive IP address changes (WiFi to cellular) without re-authentication.",["Survive network changes"]),
q("q-fin-cloud-vpc-05","aws-vpc","cloud_networking","command","medium","What is the maximum number of VPCs per region in AWS (default)?",["5"],"exact",[],"Default limit is 5 VPCs per region (can be increased via support request).",["A small default number"]),
q("q-fin-cloud-sg-04","aws-security-groups","cloud_networking","theory","medium","Can a security group span multiple VPCs?",["no","cannot","same vpc only","vpc-specific"],"contains_any",[],"No. Security groups are VPC-specific — they cannot be shared across VPCs.",["Tied to one VPC"]),
q("q-fin-auto-python-01","python-netmiko","network_automation","command","medium","What Python library is commonly used for REST API calls?",["requests","urllib","httpx"],"contains_any",[],"The 'requests' library is the standard for HTTP/REST API calls in Python network automation.",["The most popular HTTP library"]),
q("q-fin-auto-ansible-09","ansible-network","network_automation","command","medium","What file defines Ansible inventory?",["hosts","inventory","hosts.ini","hosts.yml"],"contains_any",[],"Ansible inventory is defined in hosts file (INI or YAML format) or dynamically via scripts/plugins.",["The hosts file"]),
q("q-fin-eng-eigrp-01","eigrp-basics","network_engineering","theory","medium","What type of routing protocol is EIGRP?",["advanced distance vector","hybrid","dual","diffusing update"],"contains_any",[],"EIGRP is an advanced distance-vector (hybrid) protocol using DUAL algorithm. Combines distance-vector simplicity with link-state convergence speed.",["Not purely distance-vector"]),
q("q-fin-eng-eigrp-02","eigrp-basics","network_engineering","theory","medium","What is EIGRP's administrative distance for internal routes?",["90"],"exact",[],"EIGRP internal routes have AD 90 (better than OSPF's 110). External EIGRP routes have AD 170.",["Lower than OSPF"]),
q("q-fin-fund-ftp-01","ftp-sftp","fundamentals","theory","medium","Why is SFTP preferred over FTP?",["encrypted","ssh","secure","no plaintext","encrypted channel"],"contains_any",[],"SFTP runs over SSH (encrypted). FTP sends credentials and data in plaintext. SFTP also uses a single port (22) vs FTP's complex port requirements.",["Encryption"]),
q("q-fin-fund-eth-03","ethernet","fundamentals","theory","medium","What is a jumbo frame?",["9000","larger than 1518","mtu 9000","large frame"],"contains_any",[],"Jumbo frames have MTU up to 9000 bytes (vs standard 1500). Used in data centers to reduce CPU overhead for large transfers.",["Bigger than standard"]),
q("q-fin-noc-doc-02","documentation","noc_operations","theory","medium","What is a network diagram and what types exist?",["physical","logical","topology","layer 3","layer 2","visual"],"contains_any",[],"Network diagrams: Physical (cables, ports, racks), Logical/Layer 3 (IP subnets, routing), Layer 2 (VLANs, switches). All are needed for complete documentation.",["Multiple types for different views"]),
q("q-fin-sec-zt-04","zero-trust","network_security","theory","hard","What is the role of identity in Zero Trust?",["primary perimeter","authenticate everything","identity-centric","who not where"],"contains_any",[],"In Zero Trust, identity replaces the network as the primary security perimeter. Access decisions are based on who you are, not where you are.",["Identity is the new perimeter"]),
q("q-fin-cloud-tgw-03","transit-gw","cloud_networking","scenario","hard","You have 50 VPCs that all need to communicate. What's the best architecture?",["transit gateway","tgw","hub","centralized"],"contains_any",[],"Use Transit Gateway as a central hub. All 50 VPCs attach to TGW. Avoids 1225 peering connections (50*49/2) and simplifies routing.",["Central hub vs full mesh"]),
q("q-fin-auto-cicd-04","cicd-network","network_automation","scenario","hard","A network CI/CD pipeline deploys a bad config to production. What should have prevented this?",["staging","canary","testing","validation","pre-deployment test","lab"],"contains_any",[],"Pipeline should include: syntax validation, lab/staging test, canary deployment to one device, automated verification tests, and approval gates.",["Multiple safety gates"]),
q("q-fin-eng-route-filter-01","route-filter","network_engineering","theory","hard","What is a route-map used for?",["policy","match set","redistribute","pbr","complex filtering"],"contains_any",[],"Route-maps provide complex policy control: match conditions (ACL, prefix-list, community) and set actions (metric, next-hop, community). Used in redistribution, PBR, and BGP policy.",["Match and set"]),
q("q-fin-fund-udp-01","udp-protocol","fundamentals","theory","medium","What applications commonly use UDP?",["dns","voip","video","streaming","gaming","ntp"],"contains_any",[],"UDP is used by: DNS (port 53), VoIP/video (real-time), gaming, NTP, SNMP, DHCP — applications where speed matters more than reliability.",["Real-time applications"]),
q("q-fin-noc-snmp-05","snmp-monitoring","noc_operations","command","medium","What is a MIB in SNMP?",["management information base","database","oid tree","structure","definitions"],"contains_any",[],"MIB (Management Information Base) defines the structure and meaning of managed objects (OIDs) that can be queried via SNMP.",["Defines what you can monitor"]),
q("q-fin-sec-siem-04","siem","network_security","scenario","hard","You need to detect lateral movement in your network. What SIEM rule logic?",["unusual auth","new connections","first time","baseline","anomaly"],"contains_any",[],"Detect: authentication to systems never accessed before, unusual service account usage, connections between workstations, or access outside normal hours.",["Look for new/unusual patterns"]),
q("q-fin-cloud-hybrid-03","hybrid-connectivity","cloud_networking","theory","hard","What is a VPN as backup for Direct Connect?",["failover","redundancy","backup path","if dx fails","secondary"],"contains_any",[],"A site-to-site VPN over internet serves as backup if Direct Connect fails. Lower performance but provides connectivity continuity.",["Backup over internet"]),
q("q-fin-auto-terraform-06","terraform-network","network_automation","command","medium","What command destroys all Terraform-managed resources?",["terraform destroy"],"contains_any",[],"'terraform destroy' removes all resources managed by the current Terraform configuration.",["The opposite of apply"]),
q("q-fin-eng-aci-01","aci-nsx","network_engineering","theory","hard","What is Cisco ACI?",["application centric infrastructure","sdn","data center","policy","fabric"],"contains_any",[],"ACI (Application Centric Infrastructure) is Cisco's SDN solution for data centers. Uses policy-based automation with a centralized controller (APIC) managing a leaf-spine fabric.",["Cisco's data center SDN"]),
q("q-fin-fund-ipv4-03","ipv4-addressing","fundamentals","theory","medium","What is CIDR and why was it introduced?",["classless","flexible subnetting","replace classful","variable length","conserve addresses"],"contains_any",[],"CIDR (Classless Inter-Domain Routing) replaced rigid classful addressing with flexible prefix lengths, enabling efficient IP allocation and route summarization.",["Replaced Class A/B/C"]),
]

if __name__ == "__main__":
    with open(OUTPUT_DIR / "final_quiz.json", 'w') as f:
        json.dump(FINAL, f, indent=2)
    print(f"Final: {len(FINAL)}")
    total = 0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            total += len(json.load(f))
    print(f"\nTOTAL QUESTIONS: {total}")
