#!/usr/bin/env python3
"""Generate additional quiz questions to reach 400+."""
import json
from pathlib import Path
OUTPUT_DIR = Path(__file__).parent.parent / "data" / "questions"

def q(id,topic,domain,qtype,diff,question,answers,validation,keywords,explanation,hints):
    return {"id":id,"topic_id":topic,"domain":domain,"type":qtype,"difficulty":diff,
            "question":question,"correct_answers":answers,"validation_type":validation,
            "required_keywords":keywords,"explanation":explanation,"hints":hints}

# ===================== MORE NOC (30) =====================
NOC2 = [
q("q-noc2-prom-03","prometheus","noc_operations","command","hard","Write a PromQL query to get the 5-minute rate of HTTP requests.",["rate(http_requests_total[5m])","rate(","[5m])"],"contains_any",[],"rate(http_requests_total[5m]) calculates the per-second rate over a 5-minute window.",["rate function with time window"]),
q("q-noc2-graf-02","grafana","noc_operations","theory","medium","What is a Grafana data source?",["backend","database","where data comes from","prometheus","influxdb"],"contains_any",[],"A data source is the backend that Grafana queries for metrics — Prometheus, InfluxDB, Elasticsearch, etc.",["Where the data lives"]),
q("q-noc2-zab-02","zabbix","noc_operations","theory","medium","What is a Zabbix trigger?",["condition","threshold","expression","alert condition","problem"],"contains_any",[],"A trigger is a logical expression that evaluates item data and defines when a problem state exists (e.g., CPU > 90% for 5 min).",["Defines when something is wrong"]),
q("q-noc2-libre-01","librenms","noc_operations","theory","easy","What protocol does LibreNMS primarily use for discovery?",["snmp","lldp","cdp"],"contains_any",[],"LibreNMS uses SNMP for device discovery and monitoring, with LLDP/CDP for topology mapping.",["The standard monitoring protocol"]),
q("q-noc2-netbox-01","netbox-ipam","noc_operations","theory","medium","What is NetBox used for?",["ipam","dcim","documentation","inventory","source of truth"],"contains_any",[],"NetBox is an IPAM/DCIM tool for documenting network infrastructure — IP addresses, devices, circuits, racks, and connections.",["Network documentation and IPAM"]),
q("q-noc2-tel-01","streaming-telemetry","noc_operations","theory","hard","How does streaming telemetry differ from SNMP polling?",["push","real-time","continuous","model-driven","grpc"],"contains_any",[],"Streaming telemetry pushes data continuously in real-time (gRPC/gNMI) vs SNMP's periodic pull model. Higher resolution, lower device overhead.",["Push vs pull"]),
q("q-noc2-obs-01","network-observability","noc_operations","theory","hard","What are the three pillars of observability?",["metrics logs traces","metrics","logs","traces"],"contains_any",[],"The three pillars: Metrics (what's happening), Logs (why it happened), Traces (how requests flow through systems).",["Three types of data"]),
q("q-noc2-runbook-01","runbooks2","noc_operations","scenario","medium","A junior NOC engineer gets a 'BGP peer down' alert at 3 AM. What should the runbook tell them?",["verify","check interface","escalate","contact","steps"],"contains_any",[],"Runbook should: 1) Verify alert is real, 2) Check interface status, 3) Check BGP logs, 4) Attempt clear/reset if safe, 5) Escalate if not resolved in X minutes.",["Step-by-step for 3 AM"]),
q("q-noc2-corr-01","correlation","noc_operations","theory","hard","What is event correlation in monitoring?",["relate events","reduce noise","root cause","group","deduplicate"],"contains_any",[],"Event correlation groups related alerts to identify root cause and reduce noise. E.g., 100 'host unreachable' alerts correlate to 1 'core switch down'.",["Many alerts, one cause"]),
q("q-noc2-oncall-01","oncall","noc_operations","theory","medium","What should an on-call rotation include?",["schedule","escalation","handoff","documentation","compensation"],"contains_any",[],"On-call includes: rotation schedule, escalation paths, handoff procedures, runbooks, communication tools, and fair compensation.",["More than just a schedule"]),
q("q-noc2-maint-01","maint-window","noc_operations","theory","medium","What defines a good maintenance window?",["low traffic","communication","rollback","time limit","approval"],"contains_any",[],"Good maintenance window: low-traffic period, pre-approved change, communicated to stakeholders, defined rollback plan, and time limit.",["Plan for the quiet hours"]),
q("q-noc2-dr-01","dr-network","noc_operations","theory","hard","What is RTO and RPO in disaster recovery?",["recovery time objective","recovery point objective","how long","how much data"],"contains_any",[],"RTO: maximum acceptable downtime. RPO: maximum acceptable data loss (how far back you recover to). Both drive DR design.",["Time and data loss targets"]),
q("q-noc2-cap-02","capacity-planning","noc_operations","command","medium","What formula calculates bandwidth utilization percentage?",["used / total","actual / capacity","bits / bandwidth"],"contains_any",[],"Utilization = (Actual throughput / Link capacity) × 100%. E.g., 700 Mbps on a 1 Gbps link = 70%.",["Simple division"]),
q("q-noc2-fore-01","forecasting","noc_operations","theory","hard","What data do you need for network capacity forecasting?",["historical","trend","growth rate","baseline","seasonal"],"contains_any",[],"Need: historical utilization data, growth trends, seasonal patterns, planned projects, and business growth projections.",["Past data predicts future needs"]),
q("q-noc2-vendor-01","vendor-mgmt","noc_operations","theory","medium","What should you track for vendor/circuit SLAs?",["uptime","latency","packet loss","jitter","mttr"],"contains_any",[],"Track: availability/uptime, latency, packet loss, jitter, MTTR, and compare against contracted SLA values.",["Measure what they promised"]),
q("q-noc2-inv-01","inventory-mgmt","noc_operations","theory","medium","What information should a network inventory contain?",["hostname","ip","model","serial","location","os version"],"contains_any",[],"Inventory: hostname, management IP, model, serial number, OS version, location, rack position, and support contract status.",["Everything about each device"]),
q("q-noc2-log-01","log-techniques","noc_operations","theory","medium","What is structured logging and why is it better?",["json","key-value","parseable","searchable","machine-readable"],"contains_any",[],"Structured logging uses consistent formats (JSON, key-value) making logs machine-parseable, searchable, and easier to correlate than free-text logs.",["Machines can read it"]),
q("q-noc2-config-01","config-backup","noc_operations","theory","medium","How often should network device configs be backed up?",["daily","after changes","automated","scheduled"],"contains_any",[],"Back up configs: daily (scheduled), after every change, and before maintenance. Use automation (RANCID, Oxidized, Git) for consistency.",["At minimum daily"]),
q("q-noc2-weather-01","weathermap","noc_operations","theory","easy","What is a network weathermap?",["visual","topology","utilization","traffic","color-coded"],"contains_any",[],"A weathermap is a visual network topology showing real-time link utilization with color-coding (green=low, red=high).",["Visual traffic display"]),
q("q-noc2-snmpv3-01","snmp-v3","noc_operations","command","hard","What are the three SNMPv3 security levels?",["noauthnopriv","authnopriv","authpriv","no auth","auth","priv"],"contains_any",[],"SNMPv3 levels: noAuthNoPriv (no security), authNoPriv (authentication only), authPriv (authentication + encryption).",["Three levels of security"]),
q("q-noc2-trap-01","snmp-traps2","noc_operations","theory","medium","What is the difference between an SNMP trap and an inform?",["acknowledged","reliable","no ack","udp","confirmed"],"contains_any",[],"Traps are unacknowledged (fire-and-forget, may be lost). Informs are acknowledged (receiver confirms receipt, more reliable).",["One confirms delivery"]),
q("q-noc2-troubleshoot-05","network-troubleshooting","noc_operations","command","medium","What command shows interface error counters on Cisco?",["show interface","show interfaces"],"contains_any",[],"'show interfaces <name>' displays CRC errors, collisions, input/output errors, drops, and other counters.",["show interfaces"]),
q("q-noc2-troubleshoot-06","network-troubleshooting","noc_operations","scenario","hard","Traceroute shows high latency at hop 5 but normal latency at hop 6. Is hop 5 the problem?",["no","not necessarily","icmp deprioritized","control plane","rate limited"],"contains_any",[],"Not necessarily. Routers often deprioritize ICMP (used by traceroute) in the control plane. If subsequent hops are fine, hop 5 is likely just rate-limiting ICMP responses.",["ICMP is low priority on routers"]),
q("q-noc2-troubleshoot-07","network-troubleshooting","noc_operations","command","medium","What tool combines ping and traceroute for continuous path monitoring?",["mtr","mtr command","pathping"],"contains_any",[],"MTR (My Traceroute) combines ping and traceroute, continuously showing per-hop latency and packet loss over time.",["Continuous traceroute"]),
q("q-noc2-nagios-01","nagios-mon","noc_operations","theory","medium","What are the Nagios host/service check states?",["ok warning critical unknown","up down unreachable"],"contains_any",[],"Service states: OK, WARNING, CRITICAL, UNKNOWN. Host states: UP, DOWN, UNREACHABLE.",["Four service states"]),
q("q-noc2-baseline-02","baselining","noc_operations","scenario","medium","You established a baseline showing 40% WAN utilization. Now it's consistently 75%. What action?",["investigate","capacity upgrade","plan upgrade","identify cause","growth"],"contains_any",[],"Investigate the cause (new application? growth?). If legitimate growth, plan capacity upgrade before hitting 80-90% threshold.",["Significant deviation from baseline"]),
]

# ===================== MORE SECURITY (30) =====================
SEC2 = [
q("q-sec2-fw-05","firewall-fundamentals","network_security","theory","hard","What is a next-generation firewall (NGFW)?",["application awareness","deep inspection","ips","user identity","layer 7"],"contains_any",[],"NGFW adds: application awareness (identify apps regardless of port), integrated IPS, user identity, TLS inspection, and threat intelligence.",["More than port/protocol filtering"]),
q("q-sec2-fw-06","firewall-fundamentals","network_security","scenario","hard","You need to allow Zoom but block other video apps on port 443. What firewall feature?",["application control","app-id","deep packet inspection","application awareness"],"contains_any",[],"Application-aware firewalls (NGFW) can identify specific applications within encrypted traffic using App-ID/DPI, regardless of port.",["Need to see inside the traffic"]),
q("q-sec2-vpn-04","vpn-ipsec","network_security","command","medium","What are the default IKEv2 ports?",["500","4500","udp 500","udp 4500"],"contains_any",[],"IKEv2 uses UDP 500 for initial negotiation and UDP 4500 for NAT-Traversal (NAT-T).",["Two UDP ports"]),
q("q-sec2-vpn-05","ssl-vpn2","network_security","theory","medium","What is the advantage of SSL VPN over IPsec VPN for remote users?",["no client","browser","any network","port 443","firewall friendly"],"contains_any",[],"SSL VPN works through any firewall (uses port 443), often needs no client software (browser-based), and works from any network including restrictive ones.",["Works everywhere"]),
q("q-sec2-zt-03","zero-trust","network_security","scenario","hard","A user is on the corporate network but their device fails a health check. What happens in Zero Trust?",["deny","block","quarantine","no access","remediate"],"contains_any",[],"Zero Trust denies/limits access regardless of network location. The device is quarantined or given limited access until it passes the health check.",["Location doesn't grant trust"]),
q("q-sec2-forensics-01","forensics","network_security","theory","medium","What is the first step in network forensics?",["preserve","capture","evidence","don't modify","chain of custody"],"contains_any",[],"First step: preserve evidence. Capture traffic/logs without modifying them. Establish chain of custody documentation.",["Don't contaminate evidence"]),
q("q-sec2-forensics-02","forensics","network_security","command","hard","What tcpdump command captures full packets to a file for forensic analysis?",["tcpdump -i","tcpdump -w","-s 0","capture file"],"contains_any",[],"Use 'tcpdump -i <iface> -s 0 -w capture.pcap' (-s 0 captures full packets, -w writes to file).",["Full packets to file"]),
q("q-sec2-honeypot-01","honeypots","network_security","theory","medium","What is a honeypot in network security?",["decoy","trap","fake system","attract attackers","detect"],"contains_any",[],"A honeypot is a decoy system designed to attract attackers. Any interaction with it is suspicious since legitimate users have no reason to access it.",["A trap for attackers"]),
q("q-sec2-ndr-01","ndr","network_security","theory","hard","What is NDR (Network Detection and Response)?",["network traffic analysis","detect threats","behavioral","ml","anomaly"],"contains_any",[],"NDR analyzes network traffic using behavioral analytics and ML to detect threats that bypass traditional security tools (IDS, firewall).",["AI-powered network monitoring"]),
q("q-sec2-port-01","port-sec","network_security","command","medium","What Cisco command limits a switch port to one MAC address?",["switchport port-security","port-security maximum 1","switchport port-security maximum"],"contains_any",[],"Use 'switchport port-security' and 'switchport port-security maximum 1' to limit to one MAC address.",["switchport port-security"]),
q("q-sec2-port-02","port-sec","network_security","theory","medium","What are the port-security violation modes?",["protect","restrict","shutdown"],"contains_any",[],"Violation modes: Protect (drop silently), Restrict (drop + log), Shutdown (disable port + log). Shutdown is default.",["Three modes of response"]),
q("q-sec2-dhcp-snoop-01","dhcp-snoop","network_security","theory","medium","How does DHCP snooping prevent rogue DHCP servers?",["trusted","untrusted","only trusted ports","block offers"],"contains_any",[],"DHCP snooping marks ports as trusted (where legitimate DHCP server connects) or untrusted. DHCP offers from untrusted ports are dropped.",["Trust only the real server's port"]),
q("q-sec2-bgp-sec-01","bgp-security","network_security","theory","hard","What is BGP hijacking and how is RPKI used to prevent it?",["announce prefix","steal routes","origin validation","roa","certificate"],"contains_any",[],"BGP hijacking: announcing someone else's prefixes to steal traffic. RPKI uses ROAs (Route Origin Authorizations) to cryptographically validate the legitimate origin AS.",["Validate who can announce what"]),
q("q-sec2-sdwan-01","sdwan-security","network_security","theory","medium","What security features does SD-WAN typically include?",["encryption","segmentation","firewall","zero trust","ipsec"],"contains_any",[],"SD-WAN security: IPsec encryption on all links, micro-segmentation, integrated NGFW, zero-trust access, and centralized policy management.",["Built-in security"]),
q("q-sec2-radius-01","radius-tacacs2","network_security","theory","medium","What is the difference between RADIUS and TACACS+?",["udp vs tcp","combined vs separate","cisco","authentication authorization"],"contains_any",[],"RADIUS: UDP, combines auth+authz, encrypts only password. TACACS+: TCP, separates AAA functions, encrypts entire payload. TACACS+ is more granular.",["One encrypts everything"]),
q("q-sec2-ids-04","ids-ips","network_security","theory","medium","What is a false positive vs false negative in IDS?",["alert no attack","miss real attack","wrong alert","undetected"],"contains_any",[],"False positive: alert fires but no real attack (noise). False negative: real attack occurs but no alert (missed). False negatives are more dangerous.",["Wrong alert vs missed attack"]),
q("q-sec2-seg-03","seg-patterns","network_security","theory","hard","What is the difference between north-south and east-west traffic?",["in-out vs lateral","client-server vs server-server","perimeter vs internal"],"contains_any",[],"North-south: traffic entering/leaving the network (client to server). East-west: lateral traffic between servers/workloads within the data center.",["In/out vs lateral"]),
q("q-sec2-ips-tune-01","ips-tuning","network_security","scenario","hard","Your IPS blocks a legitimate application update. How do you handle it?",["exception","whitelist","tune rule","bypass","custom rule"],"contains_any",[],"Create a specific exception/whitelist for the known-good traffic pattern. Don't disable the entire rule — create a targeted bypass.",["Targeted exception, not disable"]),
q("q-sec2-encrypt-01","net-encryption","network_security","theory","medium","What is MACsec (802.1AE)?",["layer 2 encryption","hop-by-hop","ethernet encryption","link encryption"],"contains_any",[],"MACsec (802.1AE) provides Layer 2 hop-by-hop encryption between directly connected devices. Encrypts Ethernet frames on the wire.",["Layer 2 encryption"]),
q("q-sec2-waf-02","waf","network_security","scenario","medium","A WAF is blocking legitimate API requests containing SQL keywords. How do you fix it?",["whitelist","exception","custom rule","learning mode","tune"],"contains_any",[],"Create exceptions for the specific API endpoint, use learning mode to understand normal traffic patterns, or write custom rules that are more precise.",["Targeted exceptions"]),
q("q-sec2-packet-03","packet-analysis","network_security","command","hard","What Wireshark filter shows TCP retransmissions?",["tcp.analysis.retransmission","tcp.analysis.fast_retransmission"],"contains_any",[],"Use 'tcp.analysis.retransmission' to find retransmitted packets indicating network issues.",["tcp.analysis..."]),
q("q-sec2-packet-04","packet-analysis","network_security","scenario","hard","You see many SYN packets to port 445 from one source with no SYN-ACK responses. What is this?",["port scan","syn scan","reconnaissance","scanning"],"contains_any",[],"This is a SYN scan (half-open scan) — reconnaissance activity probing for open SMB ports. The scanner sends SYN but never completes the handshake.",["Incomplete handshakes to one port"]),
q("q-sec2-nac-02","nac","network_security","scenario","medium","A contractor plugs their personal laptop into the network. What should NAC do?",["quarantine","guest vlan","restrict","deny","remediation"],"contains_any",[],"NAC should: detect unknown device, check compliance (fails — no corporate agent), place in quarantine/guest VLAN with limited access or deny entirely.",["Unknown device = restricted"]),
q("q-sec2-802-02","802-1x","network_security","theory","hard","What happens if the RADIUS server is unreachable during 802.1X authentication?",["critical vlan","fail open","fail closed","inaccessible auth bypass"],"contains_any",[],"Depends on config: fail-open (allow access to critical VLAN), fail-closed (deny all access). Most deployments use a critical VLAN for essential services.",["What if auth is down?"]),
q("q-sec2-wireless-03","wireless-security","network_security","theory","hard","What is the difference between WPA2-Personal and WPA2-Enterprise?",["psk vs radius","shared key vs individual","pre-shared vs 802.1x"],"contains_any",[],"Personal uses a Pre-Shared Key (same for everyone). Enterprise uses 802.1X/RADIUS with individual credentials per user — more secure and auditable.",["Shared key vs individual auth"]),
q("q-sec2-tls-03","tls-security","network_security","theory","hard","What is certificate pinning?",["specific certificate","expected cert","prevent mitm","trust only known","bypass ca"],"contains_any",[],"Certificate pinning hardcodes the expected certificate/public key in the application, preventing MITM attacks even if a CA is compromised.",["Trust only the specific cert you expect"]),
q("q-sec2-dns-03","dns-security","network_security","theory","medium","What is DNS over HTTPS (DoH)?",["encrypted dns","port 443","privacy","prevent snooping","https"],"contains_any",[],"DoH encrypts DNS queries inside HTTPS (port 443), preventing ISPs and network operators from seeing DNS queries. Improves privacy but complicates network security monitoring.",["DNS inside HTTPS"]),
q("q-sec2-siem-03","siem","network_security","command","hard","What is a SIEM use case for detecting brute force attacks?",["multiple failed","threshold","same source","login failures","count"],"contains_any",[],"Rule: alert when >5 failed login attempts from same source IP within 5 minutes. Correlate across multiple systems for distributed attacks.",["Count failures from same source"]),
q("q-sec2-microseg-02","microseg","network_security","theory","hard","What technology enables microsegmentation in virtualized environments?",["nsx","distributed firewall","hypervisor","software-defined","aci"],"contains_any",[],"VMware NSX, Cisco ACI, or cloud security groups provide distributed firewalls at the hypervisor/workload level for microsegmentation.",["Software-defined at the hypervisor"]),
q("q-sec2-ikev2-01","ikev2","network_security","theory","hard","What advantages does IKEv2 have over IKEv1?",["fewer messages","mobike","nat-t built-in","faster","reliable"],"contains_any",[],"IKEv2: fewer messages (4 vs 9), built-in NAT-T, MOBIKE (seamless roaming), more reliable, and simpler configuration.",["Faster and more features"]),
]

# ===================== MORE CLOUD (30) =====================
CLOUD2 = [
q("q-cloud2-vpc-04","aws-vpc","cloud_networking","scenario","hard","You need instances in a private subnet to access the internet for updates. What do you use?",["nat gateway","nat instance","nat"],"contains_any",[],"Use a NAT Gateway (or NAT instance) in a public subnet. Private subnet routes 0.0.0.0/0 to the NAT Gateway.",["Outbound only, no inbound"]),
q("q-cloud2-sg-03","aws-security-groups","cloud_networking","scenario","medium","You reference another security group as a source in a rule. What does this mean?",["instances in that group","members","any instance with that sg"],"contains_any",[],"It allows traffic from any instance associated with the referenced security group — dynamic, no IP management needed.",["Group membership, not IPs"]),
q("q-cloud2-azure-02","azure-vnet","cloud_networking","theory","medium","What is an Azure Network Security Group (NSG)?",["filter traffic","acl","allow deny","stateful","layer 4"],"contains_any",[],"NSG filters traffic to/from Azure resources using stateful rules (like AWS Security Groups + NACLs combined). Applied to subnets or NICs.",["Azure's traffic filter"]),
q("q-cloud2-azure-03","azure-vnet","cloud_networking","theory","hard","What is Azure ExpressRoute?",["dedicated connection","private","not internet","direct link"],"contains_any",[],"ExpressRoute provides a dedicated private connection from on-premises to Azure (like AWS Direct Connect). Bypasses public internet.",["Azure's Direct Connect equivalent"]),
q("q-cloud2-gcp-01","gcp-vpc-net","cloud_networking","theory","medium","How does GCP VPC differ from AWS VPC?",["global","not regional","spans regions","global resource"],"contains_any",[],"GCP VPCs are global (span all regions automatically). AWS VPCs are regional. GCP subnets are regional within the global VPC.",["GCP VPC is global"]),
q("q-cloud2-gcp-02","gcp-vpc-net","cloud_networking","theory","medium","What are GCP firewall rules applied to?",["network","vpc","tags","service accounts"],"contains_any",[],"GCP firewall rules are applied at the VPC level and can target instances by network tags or service accounts.",["Tags and service accounts"]),
q("q-cloud2-hybrid-02","hybrid-connectivity","cloud_networking","theory","hard","What is a hub-and-spoke network topology in cloud?",["central hub","shared services","transit","spokes connect to hub"],"contains_any",[],"Hub-and-spoke: central hub VPC/VNet with shared services (firewall, DNS). Spoke VPCs peer/connect to hub. All traffic flows through hub for inspection.",["Central point of control"]),
q("q-cloud2-lb-03","cloud-lb","cloud_networking","scenario","medium","Your application needs to handle WebSocket connections. Which AWS load balancer?",["alb","application load balancer"],"contains_any",[],"ALB (Application Load Balancer) supports WebSocket connections natively at Layer 7.",["Layer 7 protocol support"]),
q("q-cloud2-lb-04","cloud-lb","cloud_networking","theory","hard","What is cross-zone load balancing?",["distribute across az","all zones","even distribution","availability zones"],"contains_any",[],"Cross-zone LB distributes traffic evenly across all registered targets in all enabled AZs, regardless of which AZ the traffic enters.",["Balance across all zones"]),
q("q-cloud2-dns-02","cloud-dns2","cloud_networking","theory","medium","What is a Route 53 alias record?",["aws-specific","point to aws resource","like cname","zone apex","free"],"contains_any",[],"Alias records are AWS-specific DNS records that point to AWS resources (ELB, CloudFront, S3). Work at zone apex and are free.",["AWS-specific, works at apex"]),
q("q-cloud2-cdn-02","cdn","cloud_networking","scenario","medium","Users in Asia report slow loading of your US-hosted website. What helps?",["cdn","cloudfront","edge","cache","content delivery"],"contains_any",[],"Deploy a CDN (CloudFront, Akamai) to cache content at edge locations in Asia, reducing latency from cross-ocean requests.",["Serve from nearby"]),
q("q-cloud2-container-02","container-net","cloud_networking","theory","hard","What is a CNI plugin in Kubernetes?",["container network interface","networking","pod network","calico","flannel"],"contains_any",[],"CNI (Container Network Interface) plugins implement pod networking in Kubernetes. Examples: Calico, Flannel, Cilium, AWS VPC CNI.",["Implements pod networking"]),
q("q-cloud2-k8s-03","kubernetes-networking","cloud_networking","theory","hard","What is a Kubernetes NetworkPolicy?",["pod firewall","restrict traffic","ingress egress","namespace","label selector"],"contains_any",[],"NetworkPolicy is a Kubernetes resource that controls pod-to-pod traffic using label selectors. Like a firewall for pods.",["Firewall rules for pods"]),
q("q-cloud2-k8s-04","kubernetes-networking","cloud_networking","theory","medium","What Kubernetes Service type exposes a service externally with a cloud load balancer?",["loadbalancer","type: loadbalancer"],"contains_any",[],"Service type LoadBalancer provisions a cloud provider's load balancer to expose the service externally.",["Cloud LB integration"]),
q("q-cloud2-private-02","private-ep","cloud_networking","theory","hard","What is the difference between a gateway endpoint and an interface endpoint in AWS?",["route table vs eni","s3 dynamodb vs other","free vs cost"],"contains_any",[],"Gateway endpoints: route table entry, free, only S3/DynamoDB. Interface endpoints: ENI with private IP, costs money, works with most AWS services.",["Two types with different mechanisms"]),
q("q-cloud2-fw-01","cloud-fw","cloud_networking","theory","medium","What is AWS Network Firewall?",["managed firewall","vpc","stateful","ips","suricata"],"contains_any",[],"AWS Network Firewall is a managed stateful firewall service for VPCs with IPS capabilities (uses Suricata rules).",["Managed VPC firewall"]),
q("q-cloud2-mon-01","cloud-mon","cloud_networking","theory","medium","What AWS service monitors VPC network traffic?",["vpc flow logs","flow logs","cloudwatch"],"contains_any",[],"VPC Flow Logs capture IP traffic information for network interfaces in your VPC. Stored in CloudWatch Logs or S3.",["Flow Logs"]),
q("q-cloud2-mon-02","cloud-mon","cloud_networking","scenario","hard","You need to detect unusual traffic patterns in your VPC. What do you use?",["vpc flow logs","guardduty","traffic mirroring","anomaly detection"],"contains_any",[],"Use VPC Flow Logs for visibility, GuardDuty for automated threat detection, or Traffic Mirroring for deep packet inspection.",["Multiple tools for different depths"]),
q("q-cloud2-interconnect-01","cloud-interconnect","cloud_networking","theory","hard","What is multi-cloud networking and why is it complex?",["multiple providers","different apis","connectivity","consistent policy"],"contains_any",[],"Multi-cloud networking connects workloads across AWS/Azure/GCP. Complex due to: different APIs, overlapping IPs, inconsistent policies, and varied connectivity options.",["Different clouds, different rules"]),
q("q-cloud2-mesh-02","service-mesh2","cloud_networking","theory","hard","What is mTLS in a service mesh?",["mutual tls","both sides authenticate","certificate","zero trust","service identity"],"contains_any",[],"Mutual TLS: both client and server present certificates to authenticate each other. Service mesh automates mTLS between all services for zero-trust communication.",["Both sides prove identity"]),
q("q-cloud2-tgw-02","transit-gw","cloud_networking","theory","hard","What is Transit Gateway peering?",["connect transit gateways","inter-region","cross-region","tgw to tgw"],"contains_any",[],"TGW peering connects Transit Gateways across regions or accounts, enabling inter-region VPC communication through a centralized hub.",["Connect hubs together"]),
q("q-cloud2-dc-03","direct-connect","cloud_networking","theory","hard","What is a Direct Connect Gateway?",["multiple vpcs","multiple regions","single dx","global"],"contains_any",[],"A DX Gateway allows a single Direct Connect connection to access VPCs in multiple regions, avoiding the need for separate connections per region.",["One connection, many regions"]),
q("q-cloud2-er-01","expressroute","cloud_networking","theory","medium","What are the ExpressRoute peering types?",["private","microsoft","azure private","azure microsoft"],"contains_any",[],"ExpressRoute peering: Private peering (access VNets), Microsoft peering (access Microsoft 365 and Azure public services).",["Two peering types"]),
q("q-cloud2-waf-02","cloud-waf2","cloud_networking","scenario","medium","You need to block requests from specific countries. What cloud service?",["waf","geo restriction","geo blocking","cloudfront"],"contains_any",[],"Use WAF geo-match conditions or CloudFront geo-restriction to block requests based on geographic location.",["Geographic filtering"]),
q("q-cloud2-rt-02","aws-route-tables","cloud_networking","scenario","hard","Traffic from a private subnet needs to go through a firewall appliance before reaching the internet. How?",["route to eni","route to firewall","appliance","transit gateway"],"contains_any",[],"Route 0.0.0.0/0 to the firewall appliance's ENI (or Transit Gateway). Firewall then routes inspected traffic to NAT Gateway/IGW.",["Route through the appliance"]),
]

# ===================== MORE AUTOMATION (30) =====================
AUTO2 = [
q("q-auto2-ansible-05","ansible-network","network_automation","command","hard","What Ansible keyword runs a task only when a condition is true?",["when","when:"],"contains_any",[],"Use 'when: condition' to conditionally execute tasks. E.g., 'when: ansible_os_family == \"Cisco\"'.",["Conditional execution"]),
q("q-auto2-ansible-06","ansible-network","network_automation","theory","medium","What is an Ansible role?",["reusable","organized","directory structure","tasks vars templates"],"contains_any",[],"A role is a reusable, organized unit of automation with a standard directory structure (tasks/, vars/, templates/, handlers/).",["Organized and reusable"]),
q("q-auto2-ansible-07","ansible-roles2","network_automation","theory","hard","What is Ansible Galaxy?",["community roles","share","download","repository","marketplace"],"contains_any",[],"Ansible Galaxy is a repository for sharing and downloading community-created roles. Install with 'ansible-galaxy install <role>'.",["Community sharing platform"]),
q("q-auto2-terraform-04","terraform-network","network_automation","command","medium","What command shows what Terraform will change without applying?",["terraform plan"],"contains_any",[],"'terraform plan' shows the execution plan — what will be created, modified, or destroyed — without making changes.",["Preview changes"]),
q("q-auto2-terraform-05","terraform-network","network_automation","theory","hard","What is Terraform remote state and why use it?",["shared","team","locking","s3","backend","collaboration"],"contains_any",[],"Remote state stores Terraform state in a shared backend (S3, Azure Blob). Enables team collaboration and state locking to prevent conflicts.",["Shared state for teams"]),
q("q-auto2-netmiko-04","python-netmiko","network_automation","command","hard","How do you handle enable mode in Netmiko?",["secret","enable","net_connect.enable()"],"contains_any",[],"Add 'secret': 'enable_pass' to the device dict, then call net_connect.enable() to enter privileged mode.",["secret key and enable() method"]),
q("q-auto2-paramiko-01","paramiko2","network_automation","theory","medium","What is Paramiko?",["python ssh","low-level","ssh library","transport"],"contains_any",[],"Paramiko is a low-level Python SSH library. Netmiko is built on top of it, adding network device-specific handling.",["Low-level SSH, Netmiko's foundation"]),
q("q-auto2-textfsm-01","textfsm","network_automation","theory","medium","What is TextFSM used for?",["parse output","structured data","cli output","template","unstructured to structured"],"contains_any",[],"TextFSM parses unstructured CLI output (show commands) into structured data (lists/dicts) using templates.",["Turn CLI text into data"]),
q("q-auto2-textfsm-02","textfsm","network_automation","scenario","medium","You need to extract interface names and IPs from 'show ip interface brief' output. What tool?",["textfsm","ntc-templates","genie","parse"],"contains_any",[],"Use TextFSM with NTC-templates (pre-built templates for common show commands) to parse the output into structured data.",["Pre-built parsing templates exist"]),
q("q-auto2-openapi-01","openapi","network_automation","theory","medium","What is OpenAPI/Swagger?",["api specification","document","rest api","schema","definition"],"contains_any",[],"OpenAPI (formerly Swagger) is a specification for documenting REST APIs — defines endpoints, parameters, responses, and authentication.",["API documentation standard"]),
q("q-auto2-event-01","event-driven","network_automation","theory","hard","What is event-driven network automation?",["react to events","trigger","webhook","streaming","automatic response"],"contains_any",[],"Event-driven automation reacts to network events (link down, threshold breach) automatically triggering remediation without human intervention.",["React automatically to events"]),
q("q-auto2-batfish-01","batfish2","network_automation","scenario","hard","Before pushing a config change, you want to verify it won't break routing. What tool?",["batfish","simulation","offline analysis","pre-deployment"],"contains_any",[],"Use Batfish to analyze the proposed config offline — it simulates routing and can verify reachability, loops, and policy compliance before deployment.",["Simulate before deploying"]),
q("q-auto2-compliance-01","config-compliance2","network_automation","theory","medium","What is configuration compliance checking?",["compare to standard","drift","desired state","baseline","deviation"],"contains_any",[],"Configuration compliance verifies device configs match the desired standard/baseline. Detects drift (unauthorized changes) and non-compliance.",["Does reality match the standard?"]),
q("q-auto2-nac-01","net-as-code","network_automation","theory","hard","What does 'Network as Code' mean?",["define network in code","version control","declarative","reproducible","git"],"contains_any",[],"Network as Code: define entire network infrastructure in code (YAML, HCL, Python), version-controlled in Git, tested via CI/CD, and deployed automatically.",["Everything defined in code"]),
q("q-auto2-sim-01","network-simulation","network_automation","theory","medium","What tools can simulate network topologies for testing?",["gns3","eve-ng","containerlab","cml","packet tracer"],"contains_any",[],"GNS3, EVE-NG, Containerlab, Cisco CML, and Packet Tracer can simulate network topologies for testing automation and changes.",["Virtual labs"]),
q("q-auto2-git-03","git-configs","network_automation","command","medium","What Git command creates a new branch?",["git checkout -b","git branch","git switch -c"],"contains_any",[],"Use 'git checkout -b <branch>' or 'git switch -c <branch>' to create and switch to a new branch.",["checkout -b or switch -c"]),
q("q-auto2-git-04","git-configs","network_automation","theory","hard","What is a Git merge conflict in network config context?",["two changes same line","conflicting edits","manual resolution","both modified"],"contains_any",[],"A merge conflict occurs when two branches modify the same config section differently. Requires manual resolution to decide which change wins.",["Two people changed the same thing"]),
q("q-auto2-jinja-03","jinja2","network_automation","command","hard","How do you write a for loop in Jinja2?",["{% for","{% endfor","for item in","{% for item in list %}"],"contains_any",[],"{% for item in list %}\n  {{ item }}\n{% endfor %} — iterates over a list and renders each item.",["{% for ... %}"]),
q("q-auto2-napalm-03","napalm","network_automation","command","medium","What NAPALM method applies and commits configuration?",["load_merge_candidate","commit_config","load_replace"],"contains_any",[],"load_merge_candidate() or load_replace_candidate() loads config, then commit_config() applies it.",["Load then commit"]),
q("q-auto2-nornir-02","nornir","network_automation","theory","hard","What is Nornir's inventory system?",["hosts groups defaults","yaml","structured","host vars"],"contains_any",[],"Nornir inventory uses hosts.yaml (devices), groups.yaml (shared settings), and defaults.yaml (global defaults) for structured device management.",["YAML-based inventory"]),
q("q-auto2-scapy-02","python-scapy","network_automation","command","hard","How do you send a ping with Scapy?",["sr1(IP(dst=","ICMP","send","sr1"],"contains_any",[],"sr1(IP(dst='target')/ICMP()) sends one ICMP echo request and waits for a reply.",["sr1 with IP and ICMP layers"]),
q("q-auto2-restapi-03","rest-api-network","network_automation","theory","medium","What is an API token/key used for?",["authentication","identify","authorize","access control"],"contains_any",[],"API tokens authenticate and identify the caller, controlling access to API resources without sending username/password with each request.",["Proves who you are"]),
q("q-auto2-restapi-04","rest-api-network","network_automation","command","medium","What HTTP status code means 'Created' (successful POST)?",["201"],"exact",[],"HTTP 201 Created indicates a POST request successfully created a new resource.",["2xx success, but not 200"]),
q("q-auto2-cicd-03","cicd-network","network_automation","theory","hard","What is 'canary deployment' for network changes?",["partial rollout","one device first","test subset","gradual","validate"],"contains_any",[],"Canary deployment applies changes to a small subset of devices first, validates success, then rolls out to the rest. Limits blast radius of bad changes.",["Test on a few before all"]),
q("q-auto2-sot-02","sot","network_automation","scenario","medium","Your automation script and the actual device config differ. Which is correct?",["source of truth","sot","intended state","automation","declared state"],"contains_any",[],"The Source of Truth (intended state) is correct. The device has drifted. Automation should remediate the device to match the SoT.",["The declared state wins"]),
q("q-auto2-testing-02","infra-testing","network_automation","theory","hard","What is 'infrastructure testing' for networks?",["validate config","verify connectivity","automated checks","pytest","robot"],"contains_any",[],"Infrastructure testing: automated verification that network state matches intent — ping tests, route checks, config validation using pytest/Robot Framework.",["Automated verification"]),
q("q-auto2-netconf-03","netconf-yang","network_automation","theory","hard","What operations does NETCONF support?",["get","get-config","edit-config","copy-config","delete-config","lock"],"contains_any",[],"NETCONF operations: get, get-config, edit-config, copy-config, delete-config, lock, unlock, close-session, kill-session.",["CRUD-like operations"]),
q("q-auto2-ansible-08","ansible-network","network_automation","theory","hard","What is Ansible's 'check mode' (dry run)?",["--check","no changes","simulate","preview","what-if"],"contains_any",[],"'ansible-playbook --check' simulates execution without making changes. Shows what would change (like terraform plan).",["Preview without applying"]),
]

# ===================== MORE ENGINEERING (30) =====================
ENG2 = [
q("q-eng2-hsrp-01","hsrp-vrrp","network_engineering","theory","medium","What is HSRP used for?",["gateway redundancy","first hop","failover","virtual ip","default gateway"],"contains_any",[],"HSRP (Hot Standby Router Protocol) provides first-hop gateway redundancy. Multiple routers share a virtual IP — if active fails, standby takes over.",["Redundant default gateway"]),
q("q-eng2-hsrp-02","hsrp-vrrp","network_engineering","theory","medium","What is the difference between HSRP and VRRP?",["cisco vs standard","proprietary vs open","hsrp cisco","vrrp rfc"],"contains_any",[],"HSRP is Cisco proprietary. VRRP is an open standard (RFC 5798). Functionally similar — both provide gateway redundancy.",["One is Cisco-only"]),
q("q-eng2-ether-01","etherchannel","network_engineering","theory","medium","What is EtherChannel/Link Aggregation?",["bundle links","combine","lacp","port-channel","bandwidth"],"contains_any",[],"EtherChannel bundles multiple physical links into one logical link for increased bandwidth and redundancy.",["Combine multiple links"]),
q("q-eng2-ether-02","etherchannel","network_engineering","theory","medium","What protocol negotiates EtherChannel dynamically?",["lacp","pagp","802.3ad"],"contains_any",[],"LACP (802.3ad) is the standard protocol. PAgP is Cisco proprietary. Both negotiate link aggregation dynamically.",["Standard protocol for bundling"]),
q("q-eng2-qos-01","qos-basics","network_engineering","theory","medium","What are the three main QoS mechanisms?",["classification","queuing","policing","shaping","marking"],"contains_any",[],"QoS mechanisms: Classification/Marking (identify traffic), Queuing/Scheduling (prioritize), Policing/Shaping (rate limit).",["Identify, prioritize, limit"]),
q("q-eng2-qos-02","qos-basics","network_engineering","theory","hard","What is the difference between policing and shaping?",["drop vs buffer","hard vs soft","discard vs delay","immediate vs queue"],"contains_any",[],"Policing drops excess traffic immediately (hard limit). Shaping buffers excess traffic and sends it later (smooths bursts). Shaping adds latency.",["Drop vs delay"]),
q("q-eng2-static-01","static-routing","network_engineering","command","easy","What is the administrative distance of a static route?",["1"],"exact",[],"Static routes have AD 1 (most trusted after directly connected routes at AD 0).",["Very trusted"]),
q("q-eng2-static-02","static-routing","network_engineering","command","medium","What Cisco command creates a default static route?",["ip route 0.0.0.0 0.0.0.0"],"contains_any",[],"'ip route 0.0.0.0 0.0.0.0 <next-hop>' creates a default route (gateway of last resort).",["Route to everywhere"]),
q("q-eng2-mpls-01","mpls-basics","network_engineering","theory","medium","What is MPLS and what problem does it solve?",["label switching","fast forwarding","between layer 2 and 3","traffic engineering"],"contains_any",[],"MPLS uses labels for fast packet forwarding (between L2 and L3). Enables traffic engineering, VPNs, and QoS without complex routing lookups.",["Labels instead of IP lookups"]),
q("q-eng2-mpls-02","mpls-basics","network_engineering","theory","hard","What is an MPLS LSP?",["label switched path","path through network","ingress to egress","tunnel"],"contains_any",[],"LSP (Label Switched Path) is the path a labeled packet takes through the MPLS network from ingress to egress router.",["The path labels create"]),
q("q-eng2-vxlan-01","vxlan-basics","network_engineering","theory","hard","What is VXLAN and why is it needed?",["overlay","extend layer 2","4096 vlan limit","encapsulate","data center"],"contains_any",[],"VXLAN extends Layer 2 over Layer 3 using UDP encapsulation. Overcomes the 4096 VLAN limit (VXLAN has 16M VNIs) for large data centers.",["Overcome VLAN limits"]),
q("q-eng2-sdwan-01","sd-wan","network_engineering","theory","medium","What is SD-WAN?",["software defined wan","centralized control","multiple links","overlay","application-aware"],"contains_any",[],"SD-WAN uses software-defined networking for WAN, providing centralized control, application-aware routing across multiple links (MPLS, broadband, LTE).",["Software-defined WAN management"]),
q("q-eng2-sdwan-02","sd-wan","network_engineering","theory","hard","What advantages does SD-WAN have over traditional WAN?",["cost","agility","application awareness","centralized","multiple transports"],"contains_any",[],"SD-WAN: lower cost (use broadband), application-aware routing, centralized management, transport independence, faster deployment, and built-in encryption.",["Cheaper and smarter"]),
q("q-eng2-redist-01","redistribution","network_engineering","theory","hard","What is route redistribution and when is it needed?",["between protocols","ospf to bgp","different routing","exchange routes"],"contains_any",[],"Redistribution shares routes between different routing protocols (e.g., OSPF into BGP). Needed when merging networks or using multiple protocols.",["Share routes between protocols"]),
q("q-eng2-redist-02","redistribution","network_engineering","scenario","hard","After redistributing OSPF into EIGRP, you see a routing loop. What's the likely cause?",["mutual redistribution","feedback","route filter","missing filter"],"contains_any",[],"Mutual redistribution without proper filtering causes routes to be re-imported back into the original protocol. Use route-maps/tags to prevent feedback loops.",["Routes coming back around"]),
q("q-eng2-campus-01","campus-design","network_engineering","theory","medium","What are the three layers of the campus network design model?",["access distribution core","access","distribution","core"],"contains_any",[],"Three-tier campus: Access (user ports), Distribution (policy/routing), Core (high-speed backbone). Small networks may collapse distribution into core.",["Three tiers"]),
q("q-eng2-dc-01","dc-design","network_engineering","theory","hard","What is a spine-leaf data center architecture?",["two tier","every leaf connects to every spine","non-blocking","clos"],"contains_any",[],"Spine-leaf: every leaf switch connects to every spine switch. Provides consistent latency, non-blocking fabric, and easy horizontal scaling.",["Every leaf to every spine"]),
q("q-eng2-dc-02","dc-design","network_engineering","theory","hard","Why is spine-leaf preferred over three-tier in modern data centers?",["east-west","consistent latency","scalable","non-blocking","predictable"],"contains_any",[],"Spine-leaf handles east-west traffic better (server-to-server), provides consistent 2-hop latency, scales horizontally, and is non-blocking.",["Optimized for server-to-server"]),
q("q-eng2-wan-01","wan-tech","network_engineering","theory","medium","What WAN technologies are commonly used today?",["mpls","broadband","lte","5g","sd-wan","dedicated"],"contains_any",[],"Modern WAN: MPLS (reliable), broadband (cheap), LTE/5G (backup/remote), SD-WAN (overlay), and dedicated circuits (critical sites).",["Multiple options"]),
q("q-eng2-multicast-01","multicast","network_engineering","theory","medium","What is the multicast IP address range?",["224.0.0.0","239.255.255.255","224","class d"],"contains_any",[],"Multicast uses 224.0.0.0 to 239.255.255.255 (Class D). 224.0.0.x is link-local, 239.x.x.x is administratively scoped.",["Class D range"]),
q("q-eng2-ipv6r-01","ipv6-route","network_engineering","theory","medium","What is the IPv6 link-local address prefix?",["fe80","fe80::/10"],"contains_any",[],"IPv6 link-local addresses use fe80::/10 prefix. Auto-configured on every interface, used for neighbor discovery and routing protocol communication.",["fe80"]),
q("q-eng2-gre-01","gre","network_engineering","theory","medium","What is GRE tunneling?",["encapsulate","generic routing encapsulation","tunnel","protocol 47"],"contains_any",[],"GRE encapsulates packets inside IP packets to create point-to-point tunnels. Supports any protocol, but adds no encryption (often paired with IPsec).",["Encapsulate anything in IP"]),
q("q-eng2-pbr-01","pbr","network_engineering","theory","hard","What is Policy-Based Routing (PBR)?",["route by policy","not destination","source-based","match criteria","override routing table"],"contains_any",[],"PBR routes traffic based on criteria other than destination (source IP, protocol, port) — overrides the normal routing table.",["Route by rules, not just destination"]),
q("q-eng2-acl-01","acls","network_engineering","command","medium","What is the difference between standard and extended ACLs?",["source only vs source+dest","standard source","extended port protocol"],"contains_any",[],"Standard ACLs filter by source IP only. Extended ACLs filter by source, destination, protocol, and port numbers.",["Standard is simpler"]),
q("q-eng2-acl-02","acls","network_engineering","command","medium","Where should you place an extended ACL?",["close to source","near source","as close to source as possible"],"contains_any",[],"Place extended ACLs close to the source to block unwanted traffic early and save bandwidth on intermediate links.",["Block early"]),
q("q-eng2-redundancy-01","redundancy-design","network_engineering","theory","hard","What is the difference between active-active and active-passive redundancy?",["both active vs one standby","load sharing vs failover","utilize both vs waste one"],"contains_any",[],"Active-active: both devices handle traffic (load sharing). Active-passive: standby is idle until failover. Active-active uses resources better but is more complex.",["Both working vs one waiting"]),
q("q-eng2-rstp-01","rstp-mstp","network_engineering","theory","medium","How does RSTP improve on classic STP?",["faster convergence","seconds vs 50","proposal agreement","edge ports"],"contains_any",[],"RSTP converges in seconds (vs 50s for STP) using proposal/agreement mechanism, edge ports (like PortFast), and fewer port states.",["Much faster"]),
q("q-eng2-dhcpr-01","dhcp-relay2","network_engineering","command","medium","What Cisco command configures DHCP relay on an interface?",["ip helper-address"],"contains_any",[],"'ip helper-address <DHCP-server-IP>' on the gateway interface forwards DHCP broadcasts as unicast to the server.",["ip helper-address"]),
q("q-eng2-qosv-01","qos-voice","network_engineering","theory","hard","What QoS requirements does VoIP have?",["150ms latency","30ms jitter","1% loss","priority queue","ef"],"contains_any",[],"VoIP needs: <150ms one-way latency, <30ms jitter, <1% packet loss. Use EF (Expedited Forwarding) DSCP marking and priority queuing.",["Strict latency and loss requirements"]),
]

if __name__ == "__main__":
    with open(OUTPUT_DIR / "noc_quiz2.json", 'w') as f:
        json.dump(NOC2, f, indent=2)
    print(f"NOC2: {len(NOC2)}")
    with open(OUTPUT_DIR / "security_quiz2.json", 'w') as f:
        json.dump(SEC2, f, indent=2)
    print(f"Security2: {len(SEC2)}")
    with open(OUTPUT_DIR / "cloud_quiz2.json", 'w') as f:
        json.dump(CLOUD2, f, indent=2)
    print(f"Cloud2: {len(CLOUD2)}")
    with open(OUTPUT_DIR / "automation_quiz2.json", 'w') as f:
        json.dump(AUTO2, f, indent=2)
    print(f"Automation2: {len(AUTO2)}")
    with open(OUTPUT_DIR / "engineering_quiz2.json", 'w') as f:
        json.dump(ENG2, f, indent=2)
    print(f"Engineering2: {len(ENG2)}")
    total = 0
    for fp in OUTPUT_DIR.glob("*.json"):
        with open(fp) as f:
            total += len(json.load(f))
    print(f"\nTOTAL QUESTIONS: {total}")
